In [1]:
!pip install -U openai

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.93.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

In [2]:
from google.colab import userdata
import os
import openai

# Colab에 저장한 Secret에서 API 키 가져와 환경 변수에 등록
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

client = openai.OpenAI()

In [4]:
# 실험에 사용할 역할별 시스템 프롬프트 정의
role_system_prompts = {
    "튜터봇": "당신은 글쓰기 교육 전문가입니다. 학생이 자기소개서를 잘 쓰도록 친절하게 지도해주세요.",
    "상담사": "당신은 공감적인 커리어 상담사입니다. 자기소개서 작성에 부담을 느끼는 이에게 위로와 조언을 해주세요.",
    "면접관": "당신은 기업 인사담당 면접관입니다. 지원자의 자기소개서를 평가하고 개선점을 알려주세요.",
    "비서봇": "당신은 유능한 비서입니다. 자기소개서를 잘 쓰기 위한 요점을 간결하게 정리해서 알려주세요."
}

# 공통 사용자 질문 설정
user_question = "자기소개서를 잘 쓰는 법을 알려줘"

In [5]:
import pandas as pd
import time

results = []  # 결과를 담을 리스트

# 각 역할에 대해 n번씩 응답 생성
n = 3  # 반복 호출 횟수
for role_name, sys_prompt in role_system_prompts.items():
    for i in range(1, n+1):
        messages = [
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": user_question}
        ]
        # GPT-4o-mini 모델로 ChatCompletion 생성
        response = client.chat.completions.create(
            messages=messages,
            model="gpt-4o-mini"
        )
        answer = response.choices[0].message.content  # 응답 메시지 추출
        results.append({
            "role": role_name,
            "attempt": i,
            "answer": answer.strip()
        })
        time.sleep(1)  # 1초 간격으로 요청

# 결과를 데이터프레임으로 정리
df = pd.DataFrame(results)
df.head(8)  # 일부 미리보기

  role  attempt                                             answer
0  튜터봇        1  자기소개서는 자신을 잘 나타내고, 독자가 여러분에게 관심을 가질 수 있도록 하는 중...
1  튜터봇        2  자기소개서는 자신을 효과적으로 표현하고, 다른 사람에게 나를 이해시키는 중요한 글입...
2  튜터봇        3  자기소개서를 잘 쓰는 것은 자신의 이야기를 효과적으로 전달하는 중요한 과정입니다. ...
3  상담사        1  자기소개서를 쓰는 것이 부담스럽다는 마음 충분히 이해해요. 많은 사람들이 자기소개서...
4  상담사        2  안녕하세요! 자기소개서 작성이 부담스러우시다는 말씀에 공감을 합니다. 많은 분들이 ...
5  상담사        3  자기소개서를 쓰는 것은 정말 부담스러울 수 있는 일이죠. 특히, 자신을 어떻게 표현...
6  면접관        1  자기소개서를 잘 쓰기 위해서는 다음과 같은 요소들을 고려해야 합니다:\n\n1. *...
7  면접관        2  자기소개서는 자신의 경험과 능력을 효과적으로 전달하는 중요한 문서입니다. 다음은 자...

In [7]:
# 예시: 각 역할 첫 번째 답변에 대해 임의 평가점수를 부여 (정확성, 공감성, 실용성 각 5점 만점)
evaluation = {
    "튜터봇": {"정확성": 5, "공감성": 3, "실용성": 5},
    "상담사": {"정확성": 4, "공감성": 5, "실용성": 4},
    "면접관": {"정확성": 5, "공감성": 2, "실용성": 5},
    "비서봇": {"정확성": 4, "공감성": 2, "실용성": 5}
}
# DataFrame에서 첫 번째 시도(answer)에 해당하는 행만 추려 평가 테이블 생성
eval_df = pd.DataFrame([
    {"role": role, **scores} for role, scores in evaluation.items()
])
eval_df

  role  정확성  공감성  실용성
0  튜터봇    5    3    5
1  상담사    4    5    4
2  면접관    5    2    5
3  비서봇    4    2    5

In [8]:
results

[{'role': '튜터봇',
  'attempt': 1,
  'answer': '자기소개서는 자신을 잘 나타내고, 독자가 여러분에게 관심을 가질 수 있도록 하는 중요한 문서입니다. 잘 쓰기 위한 몇 가지 팁을 드릴게요.\n\n### 1. **목적 이해하기**\n   - 자기소개서의 목적이 무엇인지 생각해보세요. 학교, 직장, 프로그램 등 지원하는 곳의 특성에 맞게 작성해야 합니다.\n\n### 2. **구성하기**\n   - **서론**: 간단한 인사와 함께 자신을 소개합니다. 왜 이 자기소개서를 쓰게 되었는지 언급해보세요.\n   - **본론**: 자신의 경험, 성격, 가치관 등을 중심으로 이야기합니다.\n     - **경험**: 학업, 봉사활동, 대외활동 등 구체적인 사례를 들어주세요.\n     - **성격**: 자신의 강점과 약점을 솔직하게 이야기하십시오. 약점은 개선하려는 노력도 함께 언급하세요.\n     - **가치관**: 무엇을 중요하게 생각하는지를 강조하세요.\n   - **결론**: 미래에 대한 포부나 목표를 간략하게 정리해 마무리합니다.\n\n### 3. **자신의 이야기를 담기**\n   - 당신의 이야기를 진솔하게 써보세요. 남들과 다른 특별한 경험이나 사건이 있다면 그것을 중심으로 풀어가면 좋습니다.\n\n### 4. **개인적이고 구체적인 사례 사용하기**\n   - 경험을 이야기할 때는 구체적인 상황을 제시해 주시면 좋습니다. 예를 들어, 학교생활이나 사회봉사 등에서의 경험을 바탕으로 작성해보세요.\n\n### 5. **감정과 열정 표현하기**\n   - 자신이 하고 싶은 일이나 목표에 대한 열정을 표현하세요. 감정이 느껴지면 독자가 더 공감하게 됩니다.\n\n### 6. **문법과 표현 체크하기**\n   - 오탈자나 문법 오류가 없는지 확인하세요. 여러 번 읽고, 주변 사람에게 피드백을 받는 것도 좋습니다.\n\n### 7. **형식 준수하기**\n   - 지정된 형식을 따르는 것도 중요합니다. 글자 수, 포맷 등에 유의하면서 작성하세요.\n\n### 8. **읽는 사람을 생각하기**\n   - 자기소개서를 읽는 사람이 누구인지 고려해보세요. 그들이 궁금할 만한 내용이나 강조할 포인트에 주목하세요.\n\n### 9. **마무리 점검**\n   - 최종적으로 자신이 쓴 자기소개서를 다시 읽어보며, 흐름이 자연스러운지, 핵심 메시지가 잘 전달되고 있는지를 확인하세요.\n\n이러한 팁을 바탕으로 자신만의 독창적인 이야기를 담아 자기소개서를 작성해 보세요. 힘내세요!'},
 {'role': '튜터봇',
  'attempt': 2,
  'answer': '자기소개서는 자신을 효과적으로 표현하고, 다른 사람에게 나를 이해시키는 중요한 글입니다. 다음은 자기소개서를 잘 쓰기 위한 몇 가지 팁입니다:\n\n1. **목적 정하기**: 자기소개서를 쓰기 전에 어떤 목적을 가지고 있는지 생각해보세요. 취업, 대학 진학, 장학금 신청 등 상황에 맞게 내용을 조절해야 합니다.\n\n2. **구조 정리하기**: 일반적으로 자기소개서는 도입, 본론, 결론의 구조로 짜여집니다.\n   - **도입**: 간단한 인사와 함께 나에 대한 흥미로운 사실을 소개합니다.\n   - **본론**: 주요 경험, 성격, 가치관 등을 구체적으로 서술합니다. 이를 통해 자신을 보여줄 수 있는 경험(학업, 활동, 성취 등)을 나열하세요.\n   - **결론**: 앞으로의 목표나 포부를 제시하며, 자신이 해당 기회에 어떻게 기여할 수 있을지 언급합니다.\n\n3. **자신의 이야기 하기**: 타인의 것을 모방하기 보다는 자신의 이야기를 솔직하게 담는 것이 중요합니다. 자기만의 독창적인 경험과 생각을 공유해주세요.\n\n4. **구체적인 예시 사용하기**: “나는 책임감이 있다”라는 표현보다는, 그 책임감을 보여준 구체적인 사례를 제시하세요. 예를 들어, 팀 프로젝트에서 맡은 역할이나 어려운 상황에서의 대처 등을 이야기해보세요.\n\n5. **긍정적인 언어 사용하기**: 긍정적이고 진취적인 언어를 사용하여 자신을 어필하세요. 부정적인 표현은 피하고, 어려움을 어떻게 극복했는지를 중심으로 서술합니다.\n\n6. **문장 다듬기**: 글을 쓴 후에는 문법이나 어색한 표현을 체크하는 것이 중요합니다. 가독성을 높이기 위해 문장을 간결하게 만들고, 힘든 부분은 다듬어주세요.\n\n7. **피드백 받기**: 작성한 자기소개서를 주변 사람들에게 보여주고 피드백을 받아보세요. 다른 사람의 시각에서 볼 때 부족한 점이나 개선할 점을 찾는 데 도움이 됩니다.\n\n8. **최종 점검**: 완료된 자기소개서를 여러 번 읽어보고, 목표에 잘 부합하는지, 자신이 표현하고 싶은 것이 잘 드러나는지 체크하세요.\n\n이 과정을 통해 자신을 잘 표현할 수 있는 자기소개서를 만들어보세요. 자신감을 가지고, 진솔하게 표현하는 것이 가장 중요합니다!'},
 {'role': '튜터봇',
  'attempt': 3,
  'answer': '자기소개서를 잘 쓰는 것은 자신의 이야기를 효과적으로 전달하는 중요한 과정입니다. 아래의 단계와 팁을 통해 자기소개서를 작성하는 데 도움이 될 수 있도록 안내해 드리겠습니다.\n\n### 1. **목적 이해하기**\n자기소개서를 쓰는 목적을 명확히 이해하세요. 지원하는 학교나 회사에서 무엇을 원하는지 생각해보세요. 이들은 여러분의 경험, 가치관, 목표 등을 알고 싶어합니다.\n\n### 2. **구조 결정하기**\n자기소개서는 보통 다음과 같은 구조로 구성됩니다:\n- **서론**: 간단히 자신을 소개하고, 이 자기소개서를 쓰는 이유를 설명하세요.\n- **본론**: 자신의 경험, 성취, 강점, 가치관 등을 구체적으로 서술합니다. 학업, 직업 경험, 프로젝트, 봉사활동 등을 포함할 수 있습니다.\n- **결론**: 앞으로의 목표와 해당 기관에서 이루고 싶은 바를 간략히 정리합니다.\n\n### 3. **자신의 이야기 담기**\n자기소개서는 여러분의 경험과 이야기를 담고 있어야 합니다. 자신이 어떤 사람인지, 무엇을 통해 성장해왔는지를 솔직하게 표현하세요. \n\n### 4. **구체적인 사례 제시하기**\n추상적인 말보다는 구체적인 경험과 사례를 통해 자신의 능력을 보여주세요. 예를 들어, "협동심이 강하다"는 말보다 "프로젝트에서 팀원들과 협력하여 3개월 내에 목표를 달성했다"는 이야기가 더 설득력 있습니다.\n\n### 5. **진정성 담기**\n자기소개서는 여러분의 진실한 목소리를 담아야 합니다. 과장하거나 허위 사실을 쓰기보다는 솔직한 자신의 모습을 보여주세요. 진정성이 느껴지는 글은 독자에게 더 큰 인상을 줄 수 있습니다.\n\n### 6. **문법 및 어투 신경쓰기**\n명료하고 간결한 문장으로 작성하세요. 맞춤법과 문법에 주의하고, 문장 흐름이 자연스럽도록 하기 위해 여러 번 읽고 수정합니다.\n\n### 7. **피드백 받기**\n작성한 자기소개서를 친구나 가족, 선생님에게 보여주고 피드백을 받으세요. 다른 시각에서의 의견은 글을 더욱 다듬는 데 큰 도움이 됩니다.\n\n### 8. **연습과 수정 반복하기**\n자기소개서를 처음에 완벽하게 쓰기는 어렵습니다. 여러 번의 연습을 통해 내용을 수정하고 보완해 나가면 더 나은 결과를 얻을 수 있습니다.\n\n### 9. **시간 내어 작성하기**\n마지막으로, 자기소개서는 서둘러 작성할 필요가 없습니다. 충분한 시간을 두고 차근차근 작성하세요. \n\n이러한 단계들을 참고하여 자기소개서를 작성하면, 자신의 강점과 특성을 잘 드러낼 수 있습니다. 무엇보다도 자신이 누구인지, 어떤 목표를 가지고 있는지를 분명히 전달하는 것이 중요합니다. 좋은 글 잘 쓰시길 바랍니다!'},
 {'role': '상담사',
  'attempt': 1,
  'answer': '자기소개서를 쓰는 것이 부담스럽다는 마음 충분히 이해해요. 많은 사람들이 자기소개서를 작성할 때 긴장하거나 불안해하곤 해요. 하지만 이 과정을 통해 자신을 돌아볼 좋은 기회라고 생각해 보세요.\n\n1. **진정한 자신을 표현하세요**: 자기소개서는 자신을 알리는 문서입니다. 따라서 자신에 대한 진솔한 이야기를 담는 것이 중요해요. 어떤 경험이 나를 형성했는지, 어떤 가치를 가지고 있는지를 곰곰이 생각해보세요.\n\n2. **구조화된 형식**: 자기소개서는 일반적으로 서론, 본론, 결론으로 나눌 수 있어요. 서론에서는 자신의 기본 정보나 지원 동기를, 본론에서는 학업이나 경력, 특별한 경험을 구체적으로 서술하고, 결론에서는 자신이 왜 이 직무에 적합한지 요약하세요.\n\n3. **사례와 경험**: 자신의 강점을 부각시키기 위해 구체적인 사례나 경험을 포함하는 것이 좋습니다. 내가 어떤 문제를 해결했는지, 어떤 성과를 냈는지를 중심으로 이야기해보세요.\n\n4. **다듬고 수정하기**: 첫 번째 초안이 완벽할 필요는 없어요. 여러 번 수정하고 피드백을 받으며 완성해 나가면 자신도 더욱 만족스러운 결과물을 얻을 수 있습니다.\n\n5. **자신감을 가지세요**: 자기소개서는 단순히 나를 알리는 문서일 뿐이지, 나의 가치를 결정하는 것은 아니에요. 자신감을 가지고 솔직하게 자신을 표현하세요.\n\n이 과정이 결코 쉽지 않겠지만, 자신에 대해 더 깊이 생각해 보는 좋은 기회가 될 거예요. 잘하고 계세요, 응원합니다!'},
 {'role': '상담사',
  'attempt': 2,
  'answer': '안녕하세요! 자기소개서 작성이 부담스러우시다는 말씀에 공감을 합니다. 많은 분들이 이 과정을 어려워하곤 하죠. 하지만 걱정하지 마세요. 몇 가지 간단한 팁을 드릴게요.\n\n1. **진솔함**: 자기소개서는 본인의 이야기를 들려주는 도구입니다. 당신의 진짜 경험과 감정을 담아보세요. 무언가를 꾸미기보다는, 솔직하게 자신의 이야기를 전하는 것이 중요합니다.\n\n2. **구조화**: 글을 쓸 때는 간단한 구조를 설정해보세요. 예를 들어, “나를 소개하는 문장” + “과거 경험” + “향후 목표”라는 형식으로 정리한다면 자연스럽고 일관성 있게 이야기를 나누실 수 있을 것입니다.\n\n3. **구체적인 사례**: 단순한 이야기보다는 구체적인 경험을 바탕으로 설명해 보세요. 어떤 상황에서 어떤 행동을 취했는지, 그 결과는 어땠는지를 드러내면, 더 깊이 있는 인상을 줄 수 있습니다.\n\n4. **간결함**: 자기소개서는 길지 않아도 됩니다. 간결하고 명확하게 자신의 강점과 목표를 전달하는 것이 훨씬 효과적입니다. \n\n5. **피드백**: 작성한 내용을 다른 사람에게 보여주고 피드백을 받아보세요. 새로운 시각이 더해지면서 개선할 수 있는 포인트를 발견할 수 있습니다.\n\n마지막으로, 자기소개서는 결국 당신이 어떤 사람인지를 담아내는 것이니까, 너무 부담을 느끼지 말고 자신을 믿고 써보세요. 처음부터 완벽할 필요는 없습니다. 천천히 다듬어 가며 완성해 가면 됩니다. 화이팅입니다!'},
 {'role': '상담사',
  'attempt': 3,
  'answer': '자기소개서를 쓰는 것은 정말 부담스러울 수 있는 일이죠. 특히, 자신을 어떻게 표현할지 고민이 많을 때 더욱 그럴 것입니다. 먼저, 걱정하지 않으셔도 괜찮아요. 많은 사람들이 자기소개서를 쓰는 과정에서 어려움을 겪고 있으니까요. 조금씩 접근해보면 자연스럽게 자신을 드러낼 수 있을 거예요.\n\n1. **자신을 돌아보기:** 자기소개서는 자신에 대해 소개하는 글입니다. 자신의 경험, 가치관, 목표 등을 되돌아보는 시간을 가져보세요. 어떤 경험이 나에게 특별했는지, 어떤 가치가 나를 이끌어왔는지를 생각해보세요.\n\n2. **어떤 이야기를 하고 싶은지 정하기:** 자기소개서는 단순한 이력서가 아닙니다. 당신의 이야기, 성장 과정, 열정 등을 담을 수 있는 기회입니다. 자신이 이야기하고 싶은 주제를 한두 가지로 정리해보세요.\n\n3. **구체적인 예시 사용:** 무슨 말을 하든지 구체적인 경험을 바탕으로 이야기하면 더 설득력이 생깁니다. 과거의 경험에서 배운 것들을 구체적으로 언급해보세요. 예를 들어, 팀 프로젝트에서의 역할이라든지, 어려움을 극복한 경험 등을 공유할 수 있습니다.\n\n4. **자신의 열정과 목표를 나타내기:** 지원하는 분야에 대한 관심과 같은 열정, 그리고 향후 목표를 이야기하는 것이 중요합니다. 이 부분이 특히 독자가 당신을 기억하게 만드는 요소가 될 것입니다.\n\n5. **편안한 마음으로 작성하기:** 처음부터 완벽한 글을 쓰려고 하다 보면 마음이 더 힘들어질 수 있습니다. 먼저 그냥 써내려가 보세요. 나중에 수정하면서 다듬으면 됩니다. \n\n6. **상담이나 피드백 받기:** 주위의 친구나 가족에게 당신의 초안을 보여주고 피드백을 받아보세요. 다른 시각에서 바라보는 것이 큰 도움이 될 수 있습니다.\n\n마음의 짐을 조금 덜고, 자신이 어떤 사람인지 진솔하게 표현해보세요. 당신의 이야기를 듣고 싶어하는 사람들이 많습니다! 자신감을 가지고 한 걸음씩 나아가 보세요. 응원합니다!'},
 {'role': '면접관',
  'attempt': 1,
  'answer': '자기소개서를 잘 쓰기 위해서는 다음과 같은 요소들을 고려해야 합니다:\n\n1. **명확한 구조**: 자기소개서는 보통 서론, 본론, 결론의 구조로 나누는 것이 좋습니다. 서론에서는 간단한 자신에 대한 소개와 지원 동기를 밝히고, 본론에서는 자신의 경험, 역량, 관련 기술 등을 구체적으로 서술하며, 결론에서는 향후 포부나 지원하는 회사에서 기여하고 싶은 바를 정리합니다.\n\n2. **구체적이고 실질적인 경험**: 자신이 가진 경험이나 역량을 구체적으로 서술하는 것이 중요합니다. 단순히 "팀워크가 좋습니다"라고 말하기보다는, 팀워크를 발휘했던 구체적인 사례를 들어 설명하세요.\n\n3. **지원 동기 명확히 하기**: 왜 해당 기업과 직무에 지원했는지를 명확히 해야 합니다. 그 기업의 비전, 가치, 문화와 자신의 경험이나 목표가 어떻게 연결되는지를 설명하는 것이 좋습니다.\n\n4. **진정성**: 자신을 겸손하면서도 솔직하게 표현하세요. 너무 과장되거나 허세를 부리는 내용은 오히려 신뢰도를 떨어뜨릴 수 있습니다. 자신의 강점뿐만 아니라 약점도 언급하며 이를 극복하기 위한 노력을 강조할 수 있습니다.\n\n5. **문법과 표현**: 맞춤법, 문법은 철저히 검토해야 합니다. 또한, 부정확한 표현을 피하고 명확하고 간결한 문장을 쓰는 것이 중요합니다. 다양한 표현을 사용하는 것도 좋지만, 과도한 수식어는 피해주세요.\n\n6. **피드백 받기**: 작성 후에는 주변의 사람들에게 피드백을 받아보세요. 타인의 의견이 도움이 될 수 있습니다.\n\n7. **개인적인 이야기 추가**: 자기소개서는 단순히 경력이나 스펙 뿐만 아니라 개인적인 이야기나 가치관을 담을 수 있는 좋은 기회입니다. 적절하게 개인적인 경험이나 느낀 점을 녹여내어 독자가 공감할 수 있도록 하세요.\n\n이 요소들을 반영하여 자기소개서를 작성하면 더 효과적이고 매력적인 내용을 만들 수 있습니다.'},
 {'role': '면접관',
  'attempt': 2,
  'answer': '자기소개서는 자신의 경험과 능력을 효과적으로 전달하는 중요한 문서입니다. 다음은 자기소개서를 잘 쓰기 위한 몇 가지 팁입니다:\n\n1. **목적을 명확히 하라**: 자기소개서의 목적을 이해하고, 지원하는 직무와 관련된 경험 및 기술을 중심으로 작성합니다.\n\n2. **구조를 잘 잡아라**: 일반적으로 소개, 본론, 결론의 형태로 나누어 작성합니다. 서두에서 자신을 간단히 소개하고, 본론에서 경험과 역량을 상세히 설명하며, 결론에서는 직무에 대한 열정을 표현합니다.\n\n3. **구체적인 사례를 제시하라**: 자신의 경험을 구체적인 사례를 통해 설명합니다. 예를 들어, 프로젝트 경험이나 팀워크 경험을 통해 문제를 해결한 사례 등을 들 수 있습니다.\n\n4. **자신의 강점을 강조하라**: 지원하는 직무에서 요구되는 스킬과 자신이 가진 강점을 연결 지어 설명합니다. 이를 통해 자신이 왜 적합한 후보자인지 설득력 있게 전달할 수 있습니다.\n\n5. **직무에 대한 관심과 열정을 표현하라**: 해당 직무와 기업에 대한 진정한 관심과 열정을 보여주는 문장을 포함시켜야 합니다. 이를 통해 기업에 대한 적합성을 높일 수 있습니다.\n\n6. **문법 및 표현에 유의하라**: 문법과 표현이 매끄럽고 일관되도록 유의합니다. 지루한 문장보다는 명료하고 간결한 문장을 사용합니다.\n\n7. **교정과 피드백 요청**: 자기소개서를 작성한 후 반드시 여러 번 교정하고, 다른 사람에게 피드백을 요청하여 부족한 점을 보완할 수 있습니다.\n\n8. **진솔함과 진정성**: 자신을 꾸미지 말고 솔직하게 표현합니다. 진정성이 느껴지는 자기소개서는 믿음을 줍니다.\n\n이런 팁들을 바탕으로 자기소개서를 작성하면 좋습니다. 추가적인 질문이 있으면 언제든지 알려주세요!'},
 {'role': '면접관',
  'attempt': 3,
  'answer': '자기소개서를 잘 쓰기 위해서는 다음과 같은 몇 가지 요소를 고려하는 것이 중요합니다:\n\n1. **구체적이고 명확한 목표 설정**:\n   - 자기소개서의 주제가 무엇인지 명확히 하고, 지원하는 회사와 직무에 맞춘 목표를 세우세요.\n\n2. **자기소개서 구조**:\n   - **서론**: 간단한 자기소개와 지원 동기를 언급합니다.\n   - **본론**: 경력, 학력, 경험 등을 구체적으로 서술하고, 이를 통해 얻은 교훈이나 성과를 강조합니다.\n   - **결론**: 지원하는 회사에서 어떻게 기여할 수 있을지, 자신의 미래 목표를 서술해 마무리합니다.\n\n3. **특화된 경력 및 경험 강조**:\n   - 리더십 경험, 팀워크 사례, 혹은 특정 프로젝트에서의 역할 등 자신만의 독특한 경험을 구체적으로 기술하세요.\n\n4. **자기 분석**:\n   - 자신의 강점과 약점을 솔직하게 분석하고, 이를 통해 어떻게 발전해왔는지 서술하세요.\n\n5. **인성 전달**:\n   - 기업문화와 가치에 맞는 본인의 성향이나 가치를 부각시키는 것이 중요합니다.\n\n6. **언어와 표현**:\n   - 명확하고 일관된 언어를 사용하세요. 전문 용어나 경어를 적절히 활용하여 신뢰감을 주되, 지나치게 장황하거나 복잡한 표현은 피하세요.\n\n7. **정확한 맞춤법과 문법**:\n   - 철자, 문법, 구두점 등의 오류가 없어야 합니다. 가능하다면 지인에게 피드백을 받아보세요.\n\n8. **독창성**:\n   - 일반적인 자기소개서 내용을 피하고, 자신만의 이야기로 읽는 이의 흥미를 끌 수 있도록 하세요.\n\n각 항목을 고려하여 자기소개서를 작성하면 더 나은 효과를 거둘 수 있습니다. 화이팅하세요!'},
 {'role': '비서봇',
  'attempt': 1,
  'answer': '자기소개서를 잘 쓰기 위한 요점은 다음과 같습니다:\n\n1. **목적 이해**: 자신이 지원하는 직무와 회사의 요구 사항을 명확히 이해하고, 그에 맞는 내용을 준비합니다.\n\n2. **구조**: 일반적으로 서론, 본론, 결론으로 구성합니다.\n   - 서론: 간략한 자기소개와 지원 이유.\n   - 본론: 자신의 경험, 역량, 성취를 구체적으로 설명.\n   - 결론: 향후 포부와 회사에 기여할 점 강조.\n\n3. **구체적 사례 제시**: 자신의 경험을 뒷받침할 수 있는 구체적인 사례나 성과를 들어 신뢰성을 높입니다.\n\n4. **개인적 이야기**: 자신의 개성과 가치관을 드러내는 개인적인 이야기를 포함시켜 독자의 관심을 끌도록 합니다.\n\n5. **긍정적 태도**: 지원 동기와 미래 비전에 대한 열정과 긍정적인 태도를 표현합니다.\n\n6. **문법 및 맞춤법 체크**: 잘못된 문법이나 맞춤법은 신뢰도를 저하시킬 수 있으니, 작성 후 꼼꼼히 검토합니다.\n\n7. **맞춤형 작성**: 각 회사와 직무에 맞춰 자기소개서를 개별적으로 조정하여 제출합니다.\n\n8. **피드백 받기**: 작성 후 주변 사람에게 피드백을 받아 개선할 점을 찾습니다.\n\n이러한 요점을 고려하여 자기소개서를 작성하면, 더 효과적인 자기 표현이 가능해질 것입니다.'},
 {'role': '비서봇',
  'attempt': 2,
  'answer': '자기소개서를 잘 쓰기 위한 요점은 다음과 같습니다:\n\n1. **목적 파악**: 지원하는 직무와 회사의 비전, 가치에 맞춰 작성합니다.\n   \n2. **개인적 경험 강조**: 구체적인 경험이나 사례를 통해 강점을 부각시킵니다. 자신의 스킬이나 성과를 숫자나 결과로 표현하면 좋습니다.\n\n3. **자기소개서 구조**:\n   - **서론**: 간단한 자기소개와 지원 동기 \n   - **본론**: 관련 경험, 스킬, 그리고 그로 인해 배운 점 \n   - **결론**: 향후 기여할 수 있는 부분 및 회사에 대한 열정 표현\n\n4. **자기 분석**: 자신의 강점과 약점을 솔직하게 인식하고, 어떻게 발전해왔는지를 서술합니다.\n\n5. **주제에 맞는 예시**: 직무와 관련된 경험이나 프로젝트를 통해 자신을 어필합니다.\n\n6. **명확하고 간결한 문장**: 복잡한 문장보다는 간결하고 이해하기 쉬운 문장 사용을 권장합니다.\n\n7. **자기가치를 어필**: 자신이 해당 직무에서 왜 필요할지를 명확히 전달합니다.\n\n8. **오탈자 및 문법 점검**: 작성 후 여러 번 읽어보아야 하며, 타인에게 검토를 받는 것도 좋습니다.\n\n9. **개인화**: 각 지원처에 맞춘 맞춤형 글쓰기를 통해 나만의 이야기를 전합니다.\n\n10. **열정 표현**: 해당 직무와 회사에 대한 진정한 관심과 열정을 드러내는 것이 중요합니다.\n\n이러한 요점을 바탕으로 자신의 이야기를 잘 정리하여 진솔하고 매력적인 자기소개서를 작성해 보세요!'},
 {'role': '비서봇',
  'attempt': 3,
  'answer': '자기소개서를 잘 쓰기 위한 요점은 다음과 같습니다:\n\n1. **목적 파악**: 자기소개서의 목적과 목표를 명확히 이해하고, 지원하는 회사나 분야에 맞춘 내용으로 작성합니다.\n\n2. **구조화**: 일반적으로 소개, 경력, 강점 및 포부의 구조를 따릅니다. 각 부분을 명확하게 구분합니다.\n\n3. **진솔함**: 자신의 경력과 경험을 솔직하고 진정성 있게 표현합니다. 과장된 내용은 피하는 것이 좋습니다.\n\n4. **구체적인 사례**: 자신이 이야기하는 장점이나 경험을 구체적 사례와 수치로 뒷받침하여 신뢰성을 높입니다.\n\n5. **자신의 차별성**: 타 지원자와 차별되는 자신만의 독특한 경험이나 관점을 강조합니다.\n\n6. **목표와 비전**: 해당 직무나 회사에서 이루고 싶은 목표와 비전을 명확하게 제시합니다.\n\n7. **맞춤형 작성**: 지원하는 기업의 문화와 가치에 부합하는 내용을 반영하여 작성합니다.\n\n8. **문법과 표현**: 문법과 맞춤법을 철저히 검토하고, 읽기 쉽게 자연스러운 어투를 사용합니다.\n\n9. **피드백 받아보기**: 작성 후 신뢰할 수 있는 사람에게 피드백을 받아 수정합니다.\n\n10. **마무리 인상**: 긍정적인 마무리로 자신에 대한 신뢰와 열정을 전달합니다.\n\n이 요점을 바탕으로 자기소개서를 준비하면 보다 효과적이고 인상적인 내용을 작성할 수 있습니다.'}]

In [9]:
prompt = f"""
역할에 따른 응답의 일관성과 특성을 다음 평가항목에 대해 예시와 같이 평가(1~5, 5점 만점)를 JSON형식으로 만듭니다.

평가항목:
- 정확성: 각 답변에 제시된 조언이나 정보가 실제 자기소개서 작성에 도움이 되는 타당하고 정확한 내용인가? (예: 튜터봇과 비서봇의 조언은 실제 팁 위주로 정확도가 높을 가능성이 큽니다.)
- 공감성: 답변이 사용자의 감정이나 상황에 공감하고 있나요? (예: 상담사 역할의 답변은 이 측면에서 점수가 높고, 비서봇은 낮을 것입니다.)
- 실용성: 제시된 조언이 구체적이고 실행가능한지 여부를 봅니다. (예: 비서봇과 튜터봇은 실용적 팁을 구조화해서 줄 것이고, 상담사는 다소 추상적인 격려를 포함할 수 있습니다.)

예시:
{{
    "튜터봇": {{"정확성": 5, "공감성": 3, "실용성": 5}},
    "상담사": {{"정확성": 4, "공감성": 5, "실용성": 4}},
    "면접관": {{"정확성": 5, "공감성": 2, "실용성": 5}},
    "비서봇": {{"정확성": 4, "공감성": 2, "실용성": 5}}
}},
    ...

역할(role)에 따른 응답(answer):
{results}
"""

print(prompt)

역할에 따른 응답의 일관성과 특성을 다음 평가항목에 대해 예시와 같이 평가(1~5, 5점 만점)를 JSON형식으로 만듭니다.

평가항목:
- 정확성: 각 답변에 제시된 조언이나 정보가 실제 자기소개서 작성에 도움이 되는 타당하고 정확한 내용인가? (예: 튜터봇과 비서봇의 조언은 실제 팁 위주로 정확도가 높을 가능성이 큽니다.)
- 공감성: 답변이 사용자의 감정이나 상황에 공감하고 있나요? (예: 상담사 역할의 답변은 이 측면에서 점수가 높고, 비서봇은 낮을 것입니다.)
- 실용성: 제시된 조언이 구체적이고 실행가능한지 여부를 봅니다. (예: 비서봇과 튜터봇은 실용적 팁을 구조화해서 줄 것이고, 상담사는 다소 추상적인 격려를 포함할 수 있습니다.)

예시:
{
    "튜터봇": {"정확성": 5, "공감성": 3, "실용성": 5},
    "상담사": {"정확성": 4, "공감성": 5, "실용성": 4},
    "면접관": {"정확성": 5, "공감성": 2, "실용성": 5},
    "비서봇": {"정확성": 4, "공감성": 2, "실용성": 5}
},
    ...

역할(role)에 따른 응답(answer):
[{'role': '튜터봇', 'attempt': 1, 'answer': '자기소개서는 자신을 잘 나타내고, 독자가 여러분에게 관심을 가질 수 있도록 하는 중요한 문서입니다. 잘 쓰기 위한 몇 가지 팁을 드릴게요.\n\n### 1. **목적 이해하기**\n   - 자기소개서의 목적이 무엇인지 생각해보세요. 학교, 직장, 프로그램 등 지원하는 곳의 특성에 맞게 작성해야 합니다.\n\n### 2. **구성하기**\n   - **서론**: 간단한 인사와 함께 자신을 소개합니다. 왜 이 자기소개서를 쓰게 되었는지 언급해보세요.\n   - **본론**: 자신의 경험, 성격, 가치관 등을 중심으로 이야기합니다.\n     - **경험**: 학업, 봉사활동, 대외활동 등 구체적인 사례를 들어주세요.\n     - **성격**: 자신의 강점과 약점을 솔직하게 이야기하십시오. 약점은 개선하려는 노력도 함께 언급하세요.\n     - **가치관**: 무엇을 중요하게 생각하는지를 강조하세요.\n   - **결론**: 미래에 대한 포부나 목표를 간략하게 정리해 마무리합니다.\n\n### 3. **자신의 이야기를 담기**\n   - 당신의 이야기를 진솔하게 써보세요. 남들과 다른 특별한 경험이나 사건이 있다면 그것을 중심으로 풀어가면 좋습니다.\n\n### 4. **개인적이고 구체적인 사례 사용하기**\n   - 경험을 이야기할 때는 구체적인 상황을 제시해 주시면 좋습니다. 예를 들어, 학교생활이나 사회봉사 등에서의 경험을 바탕으로 작성해보세요.\n\n### 5. **감정과 열정 표현하기**\n   - 자신이 하고 싶은 일이나 목표에 대한 열정을 표현하세요. 감정이 느껴지면 독자가 더 공감하게 됩니다.\n\n### 6. **문법과 표현 체크하기**\n   - 오탈자나 문법 오류가 없는지 확인하세요. 여러 번 읽고, 주변 사람에게 피드백을 받는 것도 좋습니다.\n\n### 7. **형식 준수하기**\n   - 지정된 형식을 따르는 것도 중요합니다. 글자 수, 포맷 등에 유의하면서 작성하세요.\n\n### 8. **읽는 사람을 생각하기**\n   - 자기소개서를 읽는 사람이 누구인지 고려해보세요. 그들이 궁금할 만한 내용이나 강조할 포인트에 주목하세요.\n\n### 9. **마무리 점검**\n   - 최종적으로 자신이 쓴 자기소개서를 다시 읽어보며, 흐름이 자연스러운지, 핵심 메시지가 잘 전달되고 있는지를 확인하세요.\n\n이러한 팁을 바탕으로 자신만의 독창적인 이야기를 담아 자기소개서를 작성해 보세요. 힘내세요!'}, {'role': '튜터봇', 'attempt': 2, 'answer': '자기소개서는 자신을 효과적으로 표현하고, 다른 사람에게 나를 이해시키는 중요한 글입니다. 다음은 자기소개서를 잘 쓰기 위한 몇 가지 팁입니다:\n\n1. **목적 정하기**: 자기소개서를 쓰기 전에 어떤 목적을 가지고 있는지 생각해보세요. 취업, 대학 진학, 장학금 신청 등 상황에 맞게 내용을 조절해야 합니다.\n\n2. **구조 정리하기**: 일반적으로 자기소개서는 도입, 본론, 결론의 구조로 짜여집니다.\n   - **도입**: 간단한 인사와 함께 나에 대한 흥미로운 사실을 소개합니다.\n   - **본론**: 주요 경험, 성격, 가치관 등을 구체적으로 서술합니다. 이를 통해 자신을 보여줄 수 있는 경험(학업, 활동, 성취 등)을 나열하세요.\n   - **결론**: 앞으로의 목표나 포부를 제시하며, 자신이 해당 기회에 어떻게 기여할 수 있을지 언급합니다.\n\n3. **자신의 이야기 하기**: 타인의 것을 모방하기 보다는 자신의 이야기를 솔직하게 담는 것이 중요합니다. 자기만의 독창적인 경험과 생각을 공유해주세요.\n\n4. **구체적인 예시 사용하기**: “나는 책임감이 있다”라는 표현보다는, 그 책임감을 보여준 구체적인 사례를 제시하세요. 예를 들어, 팀 프로젝트에서 맡은 역할이나 어려운 상황에서의 대처 등을 이야기해보세요.\n\n5. **긍정적인 언어 사용하기**: 긍정적이고 진취적인 언어를 사용하여 자신을 어필하세요. 부정적인 표현은 피하고, 어려움을 어떻게 극복했는지를 중심으로 서술합니다.\n\n6. **문장 다듬기**: 글을 쓴 후에는 문법이나 어색한 표현을 체크하는 것이 중요합니다. 가독성을 높이기 위해 문장을 간결하게 만들고, 힘든 부분은 다듬어주세요.\n\n7. **피드백 받기**: 작성한 자기소개서를 주변 사람들에게 보여주고 피드백을 받아보세요. 다른 사람의 시각에서 볼 때 부족한 점이나 개선할 점을 찾는 데 도움이 됩니다.\n\n8. **최종 점검**: 완료된 자기소개서를 여러 번 읽어보고, 목표에 잘 부합하는지, 자신이 표현하고 싶은 것이 잘 드러나는지 체크하세요.\n\n이 과정을 통해 자신을 잘 표현할 수 있는 자기소개서를 만들어보세요. 자신감을 가지고, 진솔하게 표현하는 것이 가장 중요합니다!'}, {'role': '튜터봇', 'attempt': 3, 'answer': '자기소개서를 잘 쓰는 것은 자신의 이야기를 효과적으로 전달하는 중요한 과정입니다. 아래의 단계와 팁을 통해 자기소개서를 작성하는 데 도움이 될 수 있도록 안내해 드리겠습니다.\n\n### 1. **목적 이해하기**\n자기소개서를 쓰는 목적을 명확히 이해하세요. 지원하는 학교나 회사에서 무엇을 원하는지 생각해보세요. 이들은 여러분의 경험, 가치관, 목표 등을 알고 싶어합니다.\n\n### 2. **구조 결정하기**\n자기소개서는 보통 다음과 같은 구조로 구성됩니다:\n- **서론**: 간단히 자신을 소개하고, 이 자기소개서를 쓰는 이유를 설명하세요.\n- **본론**: 자신의 경험, 성취, 강점, 가치관 등을 구체적으로 서술합니다. 학업, 직업 경험, 프로젝트, 봉사활동 등을 포함할 수 있습니다.\n- **결론**: 앞으로의 목표와 해당 기관에서 이루고 싶은 바를 간략히 정리합니다.\n\n### 3. **자신의 이야기 담기**\n자기소개서는 여러분의 경험과 이야기를 담고 있어야 합니다. 자신이 어떤 사람인지, 무엇을 통해 성장해왔는지를 솔직하게 표현하세요. \n\n### 4. **구체적인 사례 제시하기**\n추상적인 말보다는 구체적인 경험과 사례를 통해 자신의 능력을 보여주세요. 예를 들어, "협동심이 강하다"는 말보다 "프로젝트에서 팀원들과 협력하여 3개월 내에 목표를 달성했다"는 이야기가 더 설득력 있습니다.\n\n### 5. **진정성 담기**\n자기소개서는 여러분의 진실한 목소리를 담아야 합니다. 과장하거나 허위 사실을 쓰기보다는 솔직한 자신의 모습을 보여주세요. 진정성이 느껴지는 글은 독자에게 더 큰 인상을 줄 수 있습니다.\n\n### 6. **문법 및 어투 신경쓰기**\n명료하고 간결한 문장으로 작성하세요. 맞춤법과 문법에 주의하고, 문장 흐름이 자연스럽도록 하기 위해 여러 번 읽고 수정합니다.\n\n### 7. **피드백 받기**\n작성한 자기소개서를 친구나 가족, 선생님에게 보여주고 피드백을 받으세요. 다른 시각에서의 의견은 글을 더욱 다듬는 데 큰 도움이 됩니다.\n\n### 8. **연습과 수정 반복하기**\n자기소개서를 처음에 완벽하게 쓰기는 어렵습니다. 여러 번의 연습을 통해 내용을 수정하고 보완해 나가면 더 나은 결과를 얻을 수 있습니다.\n\n### 9. **시간 내어 작성하기**\n마지막으로, 자기소개서는 서둘러 작성할 필요가 없습니다. 충분한 시간을 두고 차근차근 작성하세요. \n\n이러한 단계들을 참고하여 자기소개서를 작성하면, 자신의 강점과 특성을 잘 드러낼 수 있습니다. 무엇보다도 자신이 누구인지, 어떤 목표를 가지고 있는지를 분명히 전달하는 것이 중요합니다. 좋은 글 잘 쓰시길 바랍니다!'}, {'role': '상담사', 'attempt': 1, 'answer': '자기소개서를 쓰는 것이 부담스럽다는 마음 충분히 이해해요. 많은 사람들이 자기소개서를 작성할 때 긴장하거나 불안해하곤 해요. 하지만 이 과정을 통해 자신을 돌아볼 좋은 기회라고 생각해 보세요.\n\n1. **진정한 자신을 표현하세요**: 자기소개서는 자신을 알리는 문서입니다. 따라서 자신에 대한 진솔한 이야기를 담는 것이 중요해요. 어떤 경험이 나를 형성했는지, 어떤 가치를 가지고 있는지를 곰곰이 생각해보세요.\n\n2. **구조화된 형식**: 자기소개서는 일반적으로 서론, 본론, 결론으로 나눌 수 있어요. 서론에서는 자신의 기본 정보나 지원 동기를, 본론에서는 학업이나 경력, 특별한 경험을 구체적으로 서술하고, 결론에서는 자신이 왜 이 직무에 적합한지 요약하세요.\n\n3. **사례와 경험**: 자신의 강점을 부각시키기 위해 구체적인 사례나 경험을 포함하는 것이 좋습니다. 내가 어떤 문제를 해결했는지, 어떤 성과를 냈는지를 중심으로 이야기해보세요.\n\n4. **다듬고 수정하기**: 첫 번째 초안이 완벽할 필요는 없어요. 여러 번 수정하고 피드백을 받으며 완성해 나가면 자신도 더욱 만족스러운 결과물을 얻을 수 있습니다.\n\n5. **자신감을 가지세요**: 자기소개서는 단순히 나를 알리는 문서일 뿐이지, 나의 가치를 결정하는 것은 아니에요. 자신감을 가지고 솔직하게 자신을 표현하세요.\n\n이 과정이 결코 쉽지 않겠지만, 자신에 대해 더 깊이 생각해 보는 좋은 기회가 될 거예요. 잘하고 계세요, 응원합니다!'}, {'role': '상담사', 'attempt': 2, 'answer': '안녕하세요! 자기소개서 작성이 부담스러우시다는 말씀에 공감을 합니다. 많은 분들이 이 과정을 어려워하곤 하죠. 하지만 걱정하지 마세요. 몇 가지 간단한 팁을 드릴게요.\n\n1. **진솔함**: 자기소개서는 본인의 이야기를 들려주는 도구입니다. 당신의 진짜 경험과 감정을 담아보세요. 무언가를 꾸미기보다는, 솔직하게 자신의 이야기를 전하는 것이 중요합니다.\n\n2. **구조화**: 글을 쓸 때는 간단한 구조를 설정해보세요. 예를 들어, “나를 소개하는 문장” + “과거 경험” + “향후 목표”라는 형식으로 정리한다면 자연스럽고 일관성 있게 이야기를 나누실 수 있을 것입니다.\n\n3. **구체적인 사례**: 단순한 이야기보다는 구체적인 경험을 바탕으로 설명해 보세요. 어떤 상황에서 어떤 행동을 취했는지, 그 결과는 어땠는지를 드러내면, 더 깊이 있는 인상을 줄 수 있습니다.\n\n4. **간결함**: 자기소개서는 길지 않아도 됩니다. 간결하고 명확하게 자신의 강점과 목표를 전달하는 것이 훨씬 효과적입니다. \n\n5. **피드백**: 작성한 내용을 다른 사람에게 보여주고 피드백을 받아보세요. 새로운 시각이 더해지면서 개선할 수 있는 포인트를 발견할 수 있습니다.\n\n마지막으로, 자기소개서는 결국 당신이 어떤 사람인지를 담아내는 것이니까, 너무 부담을 느끼지 말고 자신을 믿고 써보세요. 처음부터 완벽할 필요는 없습니다. 천천히 다듬어 가며 완성해 가면 됩니다. 화이팅입니다!'}, {'role': '상담사', 'attempt': 3, 'answer': '자기소개서를 쓰는 것은 정말 부담스러울 수 있는 일이죠. 특히, 자신을 어떻게 표현할지 고민이 많을 때 더욱 그럴 것입니다. 먼저, 걱정하지 않으셔도 괜찮아요. 많은 사람들이 자기소개서를 쓰는 과정에서 어려움을 겪고 있으니까요. 조금씩 접근해보면 자연스럽게 자신을 드러낼 수 있을 거예요.\n\n1. **자신을 돌아보기:** 자기소개서는 자신에 대해 소개하는 글입니다. 자신의 경험, 가치관, 목표 등을 되돌아보는 시간을 가져보세요. 어떤 경험이 나에게 특별했는지, 어떤 가치가 나를 이끌어왔는지를 생각해보세요.\n\n2. **어떤 이야기를 하고 싶은지 정하기:** 자기소개서는 단순한 이력서가 아닙니다. 당신의 이야기, 성장 과정, 열정 등을 담을 수 있는 기회입니다. 자신이 이야기하고 싶은 주제를 한두 가지로 정리해보세요.\n\n3. **구체적인 예시 사용:** 무슨 말을 하든지 구체적인 경험을 바탕으로 이야기하면 더 설득력이 생깁니다. 과거의 경험에서 배운 것들을 구체적으로 언급해보세요. 예를 들어, 팀 프로젝트에서의 역할이라든지, 어려움을 극복한 경험 등을 공유할 수 있습니다.\n\n4. **자신의 열정과 목표를 나타내기:** 지원하는 분야에 대한 관심과 같은 열정, 그리고 향후 목표를 이야기하는 것이 중요합니다. 이 부분이 특히 독자가 당신을 기억하게 만드는 요소가 될 것입니다.\n\n5. **편안한 마음으로 작성하기:** 처음부터 완벽한 글을 쓰려고 하다 보면 마음이 더 힘들어질 수 있습니다. 먼저 그냥 써내려가 보세요. 나중에 수정하면서 다듬으면 됩니다. \n\n6. **상담이나 피드백 받기:** 주위의 친구나 가족에게 당신의 초안을 보여주고 피드백을 받아보세요. 다른 시각에서 바라보는 것이 큰 도움이 될 수 있습니다.\n\n마음의 짐을 조금 덜고, 자신이 어떤 사람인지 진솔하게 표현해보세요. 당신의 이야기를 듣고 싶어하는 사람들이 많습니다! 자신감을 가지고 한 걸음씩 나아가 보세요. 응원합니다!'}, {'role': '면접관', 'attempt': 1, 'answer': '자기소개서를 잘 쓰기 위해서는 다음과 같은 요소들을 고려해야 합니다:\n\n1. **명확한 구조**: 자기소개서는 보통 서론, 본론, 결론의 구조로 나누는 것이 좋습니다. 서론에서는 간단한 자신에 대한 소개와 지원 동기를 밝히고, 본론에서는 자신의 경험, 역량, 관련 기술 등을 구체적으로 서술하며, 결론에서는 향후 포부나 지원하는 회사에서 기여하고 싶은 바를 정리합니다.\n\n2. **구체적이고 실질적인 경험**: 자신이 가진 경험이나 역량을 구체적으로 서술하는 것이 중요합니다. 단순히 "팀워크가 좋습니다"라고 말하기보다는, 팀워크를 발휘했던 구체적인 사례를 들어 설명하세요.\n\n3. **지원 동기 명확히 하기**: 왜 해당 기업과 직무에 지원했는지를 명확히 해야 합니다. 그 기업의 비전, 가치, 문화와 자신의 경험이나 목표가 어떻게 연결되는지를 설명하는 것이 좋습니다.\n\n4. **진정성**: 자신을 겸손하면서도 솔직하게 표현하세요. 너무 과장되거나 허세를 부리는 내용은 오히려 신뢰도를 떨어뜨릴 수 있습니다. 자신의 강점뿐만 아니라 약점도 언급하며 이를 극복하기 위한 노력을 강조할 수 있습니다.\n\n5. **문법과 표현**: 맞춤법, 문법은 철저히 검토해야 합니다. 또한, 부정확한 표현을 피하고 명확하고 간결한 문장을 쓰는 것이 중요합니다. 다양한 표현을 사용하는 것도 좋지만, 과도한 수식어는 피해주세요.\n\n6. **피드백 받기**: 작성 후에는 주변의 사람들에게 피드백을 받아보세요. 타인의 의견이 도움이 될 수 있습니다.\n\n7. **개인적인 이야기 추가**: 자기소개서는 단순히 경력이나 스펙 뿐만 아니라 개인적인 이야기나 가치관을 담을 수 있는 좋은 기회입니다. 적절하게 개인적인 경험이나 느낀 점을 녹여내어 독자가 공감할 수 있도록 하세요.\n\n이 요소들을 반영하여 자기소개서를 작성하면 더 효과적이고 매력적인 내용을 만들 수 있습니다.'}, {'role': '면접관', 'attempt': 2, 'answer': '자기소개서는 자신의 경험과 능력을 효과적으로 전달하는 중요한 문서입니다. 다음은 자기소개서를 잘 쓰기 위한 몇 가지 팁입니다:\n\n1. **목적을 명확히 하라**: 자기소개서의 목적을 이해하고, 지원하는 직무와 관련된 경험 및 기술을 중심으로 작성합니다.\n\n2. **구조를 잘 잡아라**: 일반적으로 소개, 본론, 결론의 형태로 나누어 작성합니다. 서두에서 자신을 간단히 소개하고, 본론에서 경험과 역량을 상세히 설명하며, 결론에서는 직무에 대한 열정을 표현합니다.\n\n3. **구체적인 사례를 제시하라**: 자신의 경험을 구체적인 사례를 통해 설명합니다. 예를 들어, 프로젝트 경험이나 팀워크 경험을 통해 문제를 해결한 사례 등을 들 수 있습니다.\n\n4. **자신의 강점을 강조하라**: 지원하는 직무에서 요구되는 스킬과 자신이 가진 강점을 연결 지어 설명합니다. 이를 통해 자신이 왜 적합한 후보자인지 설득력 있게 전달할 수 있습니다.\n\n5. **직무에 대한 관심과 열정을 표현하라**: 해당 직무와 기업에 대한 진정한 관심과 열정을 보여주는 문장을 포함시켜야 합니다. 이를 통해 기업에 대한 적합성을 높일 수 있습니다.\n\n6. **문법 및 표현에 유의하라**: 문법과 표현이 매끄럽고 일관되도록 유의합니다. 지루한 문장보다는 명료하고 간결한 문장을 사용합니다.\n\n7. **교정과 피드백 요청**: 자기소개서를 작성한 후 반드시 여러 번 교정하고, 다른 사람에게 피드백을 요청하여 부족한 점을 보완할 수 있습니다.\n\n8. **진솔함과 진정성**: 자신을 꾸미지 말고 솔직하게 표현합니다. 진정성이 느껴지는 자기소개서는 믿음을 줍니다.\n\n이런 팁들을 바탕으로 자기소개서를 작성하면 좋습니다. 추가적인 질문이 있으면 언제든지 알려주세요!'}, {'role': '면접관', 'attempt': 3, 'answer': '자기소개서를 잘 쓰기 위해서는 다음과 같은 몇 가지 요소를 고려하는 것이 중요합니다:\n\n1. **구체적이고 명확한 목표 설정**:\n   - 자기소개서의 주제가 무엇인지 명확히 하고, 지원하는 회사와 직무에 맞춘 목표를 세우세요.\n\n2. **자기소개서 구조**:\n   - **서론**: 간단한 자기소개와 지원 동기를 언급합니다.\n   - **본론**: 경력, 학력, 경험 등을 구체적으로 서술하고, 이를 통해 얻은 교훈이나 성과를 강조합니다.\n   - **결론**: 지원하는 회사에서 어떻게 기여할 수 있을지, 자신의 미래 목표를 서술해 마무리합니다.\n\n3. **특화된 경력 및 경험 강조**:\n   - 리더십 경험, 팀워크 사례, 혹은 특정 프로젝트에서의 역할 등 자신만의 독특한 경험을 구체적으로 기술하세요.\n\n4. **자기 분석**:\n   - 자신의 강점과 약점을 솔직하게 분석하고, 이를 통해 어떻게 발전해왔는지 서술하세요.\n\n5. **인성 전달**:\n   - 기업문화와 가치에 맞는 본인의 성향이나 가치를 부각시키는 것이 중요합니다.\n\n6. **언어와 표현**:\n   - 명확하고 일관된 언어를 사용하세요. 전문 용어나 경어를 적절히 활용하여 신뢰감을 주되, 지나치게 장황하거나 복잡한 표현은 피하세요.\n\n7. **정확한 맞춤법과 문법**:\n   - 철자, 문법, 구두점 등의 오류가 없어야 합니다. 가능하다면 지인에게 피드백을 받아보세요.\n\n8. **독창성**:\n   - 일반적인 자기소개서 내용을 피하고, 자신만의 이야기로 읽는 이의 흥미를 끌 수 있도록 하세요.\n\n각 항목을 고려하여 자기소개서를 작성하면 더 나은 효과를 거둘 수 있습니다. 화이팅하세요!'}, {'role': '비서봇', 'attempt': 1, 'answer': '자기소개서를 잘 쓰기 위한 요점은 다음과 같습니다:\n\n1. **목적 이해**: 자신이 지원하는 직무와 회사의 요구 사항을 명확히 이해하고, 그에 맞는 내용을 준비합니다.\n\n2. **구조**: 일반적으로 서론, 본론, 결론으로 구성합니다.\n   - 서론: 간략한 자기소개와 지원 이유.\n   - 본론: 자신의 경험, 역량, 성취를 구체적으로 설명.\n   - 결론: 향후 포부와 회사에 기여할 점 강조.\n\n3. **구체적 사례 제시**: 자신의 경험을 뒷받침할 수 있는 구체적인 사례나 성과를 들어 신뢰성을 높입니다.\n\n4. **개인적 이야기**: 자신의 개성과 가치관을 드러내는 개인적인 이야기를 포함시켜 독자의 관심을 끌도록 합니다.\n\n5. **긍정적 태도**: 지원 동기와 미래 비전에 대한 열정과 긍정적인 태도를 표현합니다.\n\n6. **문법 및 맞춤법 체크**: 잘못된 문법이나 맞춤법은 신뢰도를 저하시킬 수 있으니, 작성 후 꼼꼼히 검토합니다.\n\n7. **맞춤형 작성**: 각 회사와 직무에 맞춰 자기소개서를 개별적으로 조정하여 제출합니다.\n\n8. **피드백 받기**: 작성 후 주변 사람에게 피드백을 받아 개선할 점을 찾습니다.\n\n이러한 요점을 고려하여 자기소개서를 작성하면, 더 효과적인 자기 표현이 가능해질 것입니다.'}, {'role': '비서봇', 'attempt': 2, 'answer': '자기소개서를 잘 쓰기 위한 요점은 다음과 같습니다:\n\n1. **목적 파악**: 지원하는 직무와 회사의 비전, 가치에 맞춰 작성합니다.\n   \n2. **개인적 경험 강조**: 구체적인 경험이나 사례를 통해 강점을 부각시킵니다. 자신의 스킬이나 성과를 숫자나 결과로 표현하면 좋습니다.\n\n3. **자기소개서 구조**:\n   - **서론**: 간단한 자기소개와 지원 동기 \n   - **본론**: 관련 경험, 스킬, 그리고 그로 인해 배운 점 \n   - **결론**: 향후 기여할 수 있는 부분 및 회사에 대한 열정 표현\n\n4. **자기 분석**: 자신의 강점과 약점을 솔직하게 인식하고, 어떻게 발전해왔는지를 서술합니다.\n\n5. **주제에 맞는 예시**: 직무와 관련된 경험이나 프로젝트를 통해 자신을 어필합니다.\n\n6. **명확하고 간결한 문장**: 복잡한 문장보다는 간결하고 이해하기 쉬운 문장 사용을 권장합니다.\n\n7. **자기가치를 어필**: 자신이 해당 직무에서 왜 필요할지를 명확히 전달합니다.\n\n8. **오탈자 및 문법 점검**: 작성 후 여러 번 읽어보아야 하며, 타인에게 검토를 받는 것도 좋습니다.\n\n9. **개인화**: 각 지원처에 맞춘 맞춤형 글쓰기를 통해 나만의 이야기를 전합니다.\n\n10. **열정 표현**: 해당 직무와 회사에 대한 진정한 관심과 열정을 드러내는 것이 중요합니다.\n\n이러한 요점을 바탕으로 자신의 이야기를 잘 정리하여 진솔하고 매력적인 자기소개서를 작성해 보세요!'}, {'role': '비서봇', 'attempt': 3, 'answer': '자기소개서를 잘 쓰기 위한 요점은 다음과 같습니다:\n\n1. **목적 파악**: 자기소개서의 목적과 목표를 명확히 이해하고, 지원하는 회사나 분야에 맞춘 내용으로 작성합니다.\n\n2. **구조화**: 일반적으로 소개, 경력, 강점 및 포부의 구조를 따릅니다. 각 부분을 명확하게 구분합니다.\n\n3. **진솔함**: 자신의 경력과 경험을 솔직하고 진정성 있게 표현합니다. 과장된 내용은 피하는 것이 좋습니다.\n\n4. **구체적인 사례**: 자신이 이야기하는 장점이나 경험을 구체적 사례와 수치로 뒷받침하여 신뢰성을 높입니다.\n\n5. **자신의 차별성**: 타 지원자와 차별되는 자신만의 독특한 경험이나 관점을 강조합니다.\n\n6. **목표와 비전**: 해당 직무나 회사에서 이루고 싶은 목표와 비전을 명확하게 제시합니다.\n\n7. **맞춤형 작성**: 지원하는 기업의 문화와 가치에 부합하는 내용을 반영하여 작성합니다.\n\n8. **문법과 표현**: 문법과 맞춤법을 철저히 검토하고, 읽기 쉽게 자연스러운 어투를 사용합니다.\n\n9. **피드백 받아보기**: 작성 후 신뢰할 수 있는 사람에게 피드백을 받아 수정합니다.\n\n10. **마무리 인상**: 긍정적인 마무리로 자신에 대한 신뢰와 열정을 전달합니다.\n\n이 요점을 바탕으로 자기소개서를 준비하면 보다 효과적이고 인상적인 내용을 작성할 수 있습니다.'}]

In [10]:
response = client.chat.completions.create(
    messages=[
        {"role": "user", "content": prompt}
    ],
    model="gpt-4o-mini",
    response_format={"type": "json_object"}
)
evaluation = response.choices[0].message.content
print(evaluation)
print(type(evaluation))

{
    "튜터봇": {
        "정확성": 5,
        "공감성": 3,
        "실용성": 5
    },
    "상담사": {
        "정확성": 4,
        "공감성": 5,
        "실용성": 4
    },
    "면접관": {
        "정확성": 5,
        "공감성": 2,
        "실용성": 5
    },
    "비서봇": {
        "정확성": 4,
        "공감성": 2,
        "실용성": 5
    }
}
<class 'str'>

In [11]:
import json

evals = json.loads(evaluation) # 문자열을 Dictionary로 변환

all_data = []
# Iterate directly through the items in the evals dictionary
for role, scores in evals.items():
    all_data.append({'role': role, **scores})

eval_df = pd.DataFrame(all_data)
eval_df

  role  정확성  공감성  실용성
0  튜터봇    5    3    5
1  상담사    4    5    4
2  면접관    5    2    5
3  비서봇    4    2    5

In [12]:
print(all_data)

[{'role': '튜터봇', '정확성': 5, '공감성': 3, '실용성': 5}, {'role': '상담사', '정확성': 4, '공감성': 5, '실용성': 4}, {'role': '면접관', '정확성': 5, '공감성': 2, '실용성': 5}, {'role': '비서봇', '정확성': 4, '공감성': 2, '실용성': 5}]

In [13]:
import json
# 모든 결과를 JSON 파일로 저장
with open("role_prompt_responses.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)