In [1]:
!pip install -U openai

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.93.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

In [2]:
from google.colab import userdata
import os
import openai

# Colab에 저장한 Secret에서 API 키 가져와 환경 변수에 등록
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

client = openai.OpenAI()

In [3]:
import time
from pprint import pprint

roles_models = [
    ("당신은 친절한 초등학교 과학선생님입니다.", "gpt-4o-mini"),
    ("당신은 물리학과 대학교수입니다.", "gpt-4o-mini"),
    ("당신은 친절한 초등학교 과학선생님입니다.", "gpt-3.5-turbo")
]
prompt = "양자이론이 뭐에요?"
responses = []

for role, model in roles_models:
    response = client.chat.completions.create(
        messages= [
            {"role": "system", "content": role},
            {"role": "user", "content": prompt}
        ],
        model=model
    )
    responses.append(response.choices[0].message.content)
    time.sleep(1)

# 응답 내용 추출
pprint(responses)

['양자이론은 물리학의 한 분야로, 아주 작은 입자들, 즉 원자와 그 안에 있는 전자, 양성자, 중성자 같은 물질의 기본 구성 요소가 어떻게 '
 '행동하는지를 설명하는 이론이에요. 이 이론은 특히 현미경적으로 작은 세계에서 일어나는 방식과 관련이 있습니다.\n'
 '\n'
 "양자이론의 주요 개념 중 하나는 '양자'라는 것입니다. 양자는 에너지와 물질이 가질 수 있는 가장 작은 단위인데, 특정한 조건에서 "
 '에너지가 끊기거나 양자화되어 존재한다는 것을 의미해요. 예를 들어, 전자는 특정한 궤도에서만 존재할 수 있고 그 궤도 사이에 있는 '
 '에너지를 가질 수 없어요.\n'
 '\n'
 "또한, 양자역학에서는 물체가 동시에 여러 상태를 가질 수 있는 '중첩'이나, 두 개의 입자가 서로 영향을 주는 '얽힘' 같은 신기한 "
 '현상도 포함되어 있어요. 이런 개념들은 우리가 일상에서 경험하는 세계와는 매우 다르기 때문에 조금 복잡하게 느껴질 수 있지만, 현대 '
 '과학, 특히 반도체, 레이저, 그리고 컴퓨터 기술 등에서 매우 중요한 역할을 하고 있습니다.\n'
 '\n'
 '쉽게 말해, 양자이론은 정말 작고 신비한 세계가 어떻게 움직이는지를 이해하는 열쇠라고 할 수 있어요!',
 '양자이론(Quantum Theory)은 물리학의 한 분야로, 원자 및 아원자 입자의 행동을 설명하는 이론입니다. 고전 물리학으로는 설명할 '
 '수 없는 범위의 현상들을 이해하기 위해 개발되었습니다. 양자역학(Quantum Mechanics)은 이론의 기본적인 틀을 제공하며, '
 '다음과 같은 몇 가지 주요 개념이 포함됩니다.\n'
 '\n'
 '1. **양자화**: 에너지가 연속적이지 않고, 특정한 단위(양자)로 존재한다는 개념입니다. 예를 들어, 전자는 특정한 에너지 준위를 '
 '가지고만 존재할 수 있습니다.\n'
 '\n'
 '2. **파동-입자 이중성**: 입자는 동시에 파동의 성질을 지니고 있으며, 이는 빛과 같은 입자에서 특히 두드러집니다. 즉, 광자는 '
 '빛의 파동 성질과 동시에 입자의 성질을 갖습니다.\n'
 '\n'
 '3. **불확정성 원리**: 하이젠베르크의 불확정성 원리에 따르면, 입자의 위치와 속도를 동시에 정확히 알 수 없다는 것입니다. 한 값을 '
 '더 정확히 측정할수록 다른 값에 대한 불확실성이 커집니다.\n'
 '\n'
 '4. **관측의 역할**: 양자 상태는 관측되기 전까지 여러 가지 가능성의 중첩 상태에 있을 수 있으며, 관측을 통해 특정한 상태로 '
 "'붕괴'하는 경향이 있습니다.\n"
 '\n'
 '5. **양자 얽힘**: 두 개 이상의 입자가 서로의 상태에 영향을 미치는 현상으로, 이들 입자가 서로 멀리 떨어져 있어도 상관없이 '
 '상태가 연관되어 있는 것을 의미합니다.\n'
 '\n'
 '양자이론은 현대 물리학에서 중요한 역할을 하며, 반도체, 레이저, 초전도체 등 다양한 기술의 기초를 제공합니다. 이러한 이론은 또한 '
 '다양한 실험을 통해 검증되었으며, 물리학의 여러 분야에서 매우 중요한 도구로 자리 잡고 있습니다.',
 '양자이론은 원자와 입자들이 빛과 더불어 동작하는 방법을 설명하는 물리 이론입니다. 양자이론은 미시세계에서의 현상을 설명하고 예측하는 데 '
 '사용되는 이론입니다. 양자이론은 20세기 초기에 개발되었으며, 양자역학과 양자장론으로 구분됩니다. 양자이론은 현재 물리학, 화학, '
 '전자공학 및 다양한 분야에서 핵심적인 개념으로 사용되고 있습니다.']

In [4]:
import pandas as pd

responses_df = pd.DataFrame(responses, columns=["response"])
responses_df

                                            response
0  양자이론은 물리학의 한 분야로, 아주 작은 입자들, 즉 원자와 그 안에 있는 전자,...
1  양자이론(Quantum Theory)은 물리학의 한 분야로, 원자 및 아원자 입자의...
2  양자이론은 원자와 입자들이 빛과 더불어 동작하는 방법을 설명하는 물리 이론입니다. ...

In [5]:
prompt_eval = f"""
응답 텍스트에 대한 평가(1~5, 5점 만점)를 평가항목에 따라 예시와 같이 JSON형식으로 만들어주세요.

평가항목:
- 정확성: 응답 내용의 사실적 정확도와 일관성
- 일관성: 지정된 역할이나 톤을 응답이 꾸준히 유지하는 정도
- 톤 적절성: 목표 사용자나 상황에 맞는 어조/스타일 사용 여부
- 포맷 적합성: 요구된 출력 형식과 논리 구조를 제대로 따른 정도

예시:
[
    {{"정확성": 5, "일관성": 5, "톤 적절성": 5, "포맷 적합성": 5 }},
    {{"정확성": 4, "일관성": 4, "톤 적절성": 4, "포맷 적합성": 4 }},
    {{"정확성": 3, "일관성": 3, "톤 적절성": 3, "포맷 적합성": 3 }}
]

응답 텍스트:
{responses_df.to_markdown()} # LLM이 입력과 출력에 markdown에 대한 학습이 잘되어 있어 변환하는 것이 좋다.
"""

print(prompt_eval)

응답 텍스트에 대한 평가(1~5, 5점 만점)를 평가항목에 따라 예시와 같이 JSON형식으로 만들어주세요.

평가항목:
- 정확성: 응답 내용의 사실적 정확도와 일관성
- 일관성: 지정된 역할이나 톤을 응답이 꾸준히 유지하는 정도
- 톤 적절성: 목표 사용자나 상황에 맞는 어조/스타일 사용 여부
- 포맷 적합성: 요구된 출력 형식과 논리 구조를 제대로 따른 정도

예시:
[
    {"정확성": 5, "일관성": 5, "톤 적절성": 5, "포맷 적합성": 5 },
    {"정확성": 4, "일관성": 4, "톤 적절성": 4, "포맷 적합성": 4 },
    {"정확성": 3, "일관성": 3, "톤 적절성": 3, "포맷 적합성": 3 }
]

응답 텍스트:
|    | response                                                                                                                                                                                                                                                                                                                                          |
|---:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | 양자이론은 물리학의 한 분야로, 아주 작은 입자들, 즉 원자와 그 안에 있는 전자, 양성자, 중성자 같은 물질의 기본 구성 요소가 어떻게 행동하는지를 설명하는 이론이에요. 이 이론은 특히 현미경적으로 작은 세계에서 일어나는 방식과 관련이 있습니다.                                                                                                     |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 양자이론의 주요 개념 중 하나는 '양자'라는 것입니다. 양자는 에너지와 물질이 가질 수 있는 가장 작은 단위인데, 특정한 조건에서 에너지가 끊기거나 양자화되어 존재한다는 것을 의미해요. 예를 들어, 전자는 특정한 궤도에서만 존재할 수 있고 그 궤도 사이에 있는 에너지를 가질 수 없어요.                                                                |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 또한, 양자역학에서는 물체가 동시에 여러 상태를 가질 수 있는 '중첩'이나, 두 개의 입자가 서로 영향을 주는 '얽힘' 같은 신기한 현상도 포함되어 있어요. 이런 개념들은 우리가 일상에서 경험하는 세계와는 매우 다르기 때문에 조금 복잡하게 느껴질 수 있지만, 현대 과학, 특히 반도체, 레이저, 그리고 컴퓨터 기술 등에서 매우 중요한 역할을 하고 있습니다. |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 쉽게 말해, 양자이론은 정말 작고 신비한 세계가 어떻게 움직이는지를 이해하는 열쇠라고 할 수 있어요!                                                                                                                                                                                                                                                 |
|  1 | 양자이론(Quantum Theory)은 물리학의 한 분야로, 원자 및 아원자 입자의 행동을 설명하는 이론입니다. 고전 물리학으로는 설명할 수 없는 범위의 현상들을 이해하기 위해 개발되었습니다. 양자역학(Quantum Mechanics)은 이론의 기본적인 틀을 제공하며, 다음과 같은 몇 가지 주요 개념이 포함됩니다.                                                          |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 1. **양자화**: 에너지가 연속적이지 않고, 특정한 단위(양자)로 존재한다는 개념입니다. 예를 들어, 전자는 특정한 에너지 준위를 가지고만 존재할 수 있습니다.                                                                                                                                                                                           |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 2. **파동-입자 이중성**: 입자는 동시에 파동의 성질을 지니고 있으며, 이는 빛과 같은 입자에서 특히 두드러집니다. 즉, 광자는 빛의 파동 성질과 동시에 입자의 성질을 갖습니다.                                                                                                                                                                         |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 3. **불확정성 원리**: 하이젠베르크의 불확정성 원리에 따르면, 입자의 위치와 속도를 동시에 정확히 알 수 없다는 것입니다. 한 값을 더 정확히 측정할수록 다른 값에 대한 불확실성이 커집니다.                                                                                                                                                           |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 4. **관측의 역할**: 양자 상태는 관측되기 전까지 여러 가지 가능성의 중첩 상태에 있을 수 있으며, 관측을 통해 특정한 상태로 '붕괴'하는 경향이 있습니다.                                                                                                                                                                                              |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 5. **양자 얽힘**: 두 개 이상의 입자가 서로의 상태에 영향을 미치는 현상으로, 이들 입자가 서로 멀리 떨어져 있어도 상관없이 상태가 연관되어 있는 것을 의미합니다.                                                                                                                                                                                    |
|    |                                                                                                                                                                                                                                                                                                                                                   |
|    | 양자이론은 현대 물리학에서 중요한 역할을 하며, 반도체, 레이저, 초전도체 등 다양한 기술의 기초를 제공합니다. 이러한 이론은 또한 다양한 실험을 통해 검증되었으며, 물리학의 여러 분야에서 매우 중요한 도구로 자리 잡고 있습니다.                                                                                                                     |
|  2 | 양자이론은 원자와 입자들이 빛과 더불어 동작하는 방법을 설명하는 물리 이론입니다. 양자이론은 미시세계에서의 현상을 설명하고 예측하는 데 사용되는 이론입니다. 양자이론은 20세기 초기에 개발되었으며, 양자역학과 양자장론으로 구분됩니다. 양자이론은 현재 물리학, 화학, 전자공학 및 다양한 분야에서 핵심적인 개념으로 사용되고 있습니다.             | # LLM이 입력과 출력에 markdown에 대한 학습이 잘되어 있어 변환하는 것이 좋다.

In [6]:
response = client.chat.completions.create(
    messages=[
        {"role": "user", "content": prompt_eval}
    ],
    model="gpt-4o",
    response_format={"type": "json_object"}
)
evaluation = response.choices[0].message.content
print(evaluation)
print(type(evaluation))

{
    "평가결과": [
        {
            "정확성": 5,
            "일관성": 5,
            "톤 적절성": 5,
            "포맷 적합성": 5
        },
        {
            "정확성": 5,
            "일관성": 5,
            "톤 적절성": 5,
            "포맷 적합성": 5
        },
        {
            "정확성": 4,
            "일관성": 4,
            "톤 적절성": 4,
            "포맷 적합성": 4
        }
    ]
}
<class 'str'>

In [8]:
import json

evals = json.loads(evaluation) # 문자열을 Dictionary로 변환

print(evals)

all_data = []
for scores in evals["평가결과"]: # Changed 'responses' to '평가'
    all_data.append({**scores})

eval_df = pd.DataFrame(all_data)
eval_df

{'평가결과': [{'정확성': 5, '일관성': 5, '톤 적절성': 5, '포맷 적합성': 5}, {'정확성': 5, '일관성': 5, '톤 적절성': 5, '포맷 적합성': 5}, {'정확성': 4, '일관성': 4, '톤 적절성': 4, '포맷 적합성': 4}]}

   정확성  일관성  톤 적절성  포맷 적합성
0    5    5      5       5
1    5    5      5       5
2    4    4      4       4

In [ ]:
roles_models_df = pd.DataFrame(roles_models, columns=["role", "model"])
roles_models_df

                     role          model
0  당신은 친절한 초등학교 과학선생님입니다.    gpt-4o-mini
1       당신은 물리학과 대학교수입니다.    gpt-4o-mini
2  당신은 친절한 초등학교 과학선생님입니다.  gpt-3.5-turbo

In [ ]:
result_df = pd.concat([roles_models_df, responses_df, eval_df], axis=1)
result_df

,role,model,response,정확성,일관성,톤 적절성,포맷 적합성
0,당신은 친절한 초등학교 과학선생님입니다.,gpt-4o-mini,양자이론은 물질과 에너지가 아주 작은 입자 수준에서 어떻게 행동하는지를 설명하는 과...,5,5,5,5
1,당신은 물리학과 대학교수입니다.,gpt-4o-mini,"양자 이론은 물리학의 한 분야로, 미시 세계에서 물질과 에너지가 어떻게 상호작용하는...",5,5,5,5
2,당신은 친절한 초등학교 과학선생님입니다.,gpt-3.5-turbo,양자 이론은 원자와 입자들의 행동을 설명하는 물리 이론입니다. 양자 이론은 물리학에...,5,5,5,5

In [ ]:
result_df.to_csv("result_evaluation.csv", index=False)

In [ ]:
result_df

,role,model,response,정확성,일관성,톤 적절성,포맷 적합성
0,당신은 친절한 초등학교 과학선생님입니다.,gpt-4o-mini,양자이론은 물질과 에너지가 아주 작은 입자 수준에서 어떻게 행동하는지를 설명하는 과...,5,5,5,5
1,당신은 물리학과 대학교수입니다.,gpt-4o-mini,"양자 이론은 물리학의 한 분야로, 미시 세계에서 물질과 에너지가 어떻게 상호작용하는...",5,5,5,5
2,당신은 친절한 초등학교 과학선생님입니다.,gpt-3.5-turbo,양자 이론은 원자와 입자들의 행동을 설명하는 물리 이론입니다. 양자 이론은 물리학에...,5,5,5,5

In [ ]:
# 각 지표별 평균 점수
result_df[["정확성","일관성","톤 적절성","포맷 적합성"]].mean()

정확성       5.0
일관성       5.0
톤 적절성     5.0
포맷 적합성    5.0
dtype: float64

In [ ]:
# 특정 조건 필터링: 정확성 3 이하인 사례 출력
result_df[result_df["정확성"] <= 3][["model","role","정확성","response"]]

Empty DataFrame
Columns: [model, role, 정확성, response]
Index: []