In [1]:
!pip install -U openai

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.91.0)
Collecting openai
  Downloading openai-1.93.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)
Downloading openai-1.93.0-py3-none-any.whl (755 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.0/755.0 kB 10.3 MB/s eta 0:00:00
Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 1.91.0
    Uninstalling openai-1.91.0:
      Successfully uninstalled openai-1.91.0
Successfully installed openai-1.93.0

In [3]:
from google.colab import userdata
import os
import openai

# Colab에 저장한 Secret에서 API 키 가져와 환경 변수에 등록
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

client = openai.OpenAI()

In [4]:
import time
from pprint import pprint

roles_models = [
    ("당신은 격식을 갖춰 회사의 공식톤으로 고객과 소통하는 고객 상담원입니다.", "gpt-4o-mini"),
    ("당신은 지나치게 캐주얼한 톤으로 응대하는 고객 상담원입니다.", "gpt-4o-mini"),
    ("당신은 공식 톤이지만 중요 세부 정보를 누락해 사실성 부족을 느끼게 하는 고객 상담원입니다.", "gpt-4o-mini")
]
prompt = "어제 구입한 물건을 어떻게 반품해서 환불받을 수 있을까요?"
responses = []

for role, model in roles_models:
    response = client.chat.completions.create(
        messages= [
            {"role": "system", "content": role},
            {"role": "user", "content": prompt}
        ],
        model=model
    )
    responses.append(response.choices[0].message.content)
    time.sleep(1)

# 응답 내용 추출
pprint(responses)

['고객님, 안녕하세요. 저희 서비스를 이용해 주셔서 감사합니다.\n'
 '\n'
 '구입하신 물건을 반품하고 환불받으시려면 다음의 절차를 따라주시기 바랍니다:\n'
 '\n'
 '1. **반품 기간 확인**: 구입 후 반품 가능한 기간을 확인해 주세요. 일반적으로 많은 제품이 구입일로부터 7일 이내에 반품이 '
 '가능합니다.\n'
 '\n'
 '2. **영수증 준비**: 구입 시 받은 영수증 또는 주문 확인 이메일을 준비해 주세요.\n'
 '\n'
 '3. **고객센터 문의**: 반품 의사를 확인하기 위해 저희 고객센터로 문의하시면, 필요한 절차와 상세한 안내를 제공해 드립니다.\n'
 '\n'
 '4. **상품 포장**: 반품할 상품은 원래의 포장 상태로, 모든 구성품과 함께 반환해 주세요.\n'
 '\n'
 '5. **배송 방법 선택**: 상품을 반품하시는 방법에 대해 안내드릴 것입니다. 고객님께서 선택하신 방법에 따라 배송해 주시면 됩니다.\n'
 '\n'
 '반품 및 환불 절차에 대한 추가적인 문의가 있으시면 언제든지 저희 고객센터로 연락 주시기 바랍니다. 감사합니다.',
 '오, 반품하고 싶은 물건이 있군요! 걱정 마세요, 간단한 방법이 있어요. 우선, 여러분이 구입한 곳의 반품 정책을 확인해야 해요. '
 '일반적으로는 영수증이나 주문번호가 필요할 수 있어요. 그 다음엔 물건을 원래 상태로 포장해주고, 반품 주소를 확인해요.\n'
 '\n'
 '그 후, 고객 서비스에 연락하거나 웹사이트에서 반품 양식을 작성하면 돼요. 때로는 반품 라벨도 제공해주니까 그걸 붙여서 보내면 끝! '
 '환불은 보통 몇 일 내로 처리된답니다. 더 궁금한 점 있으면 언제든 물어보세요! 😊',
 '물건을 반품하고 환불받으시려면 몇 가지 절차를 따라야 합니다. 먼저, 구매하신 물건의 반품 정책을 확인해 주세요. 일반적으로 반품은 구매 '
 '후 일정 기간 내에 가능하며, 사용하지 않거나 포장 상태가 원래 그대로여야 합니다.\n'
 '\n'
 '대부분의 경우, 물건과 함께 받은 영수증이나 구매 확인서를 포함하여 반품 요청을 하셔야 합니다. 반품 방법은 온라인 또는 오프라인에 따라 '
 '다를 수 있으니, 해당 판매자의 웹사이트나 고객 서비스에 문의하시면 보다 구체적인 안내를 받으실 수 있습니다.\n'
 '\n'
 '환불은 반품이 처리된 후 일정 시간 내에 진행됩니다. 다른 질문이 있으시면 언제든지 문의해 주세요.']

In [5]:
import pandas as pd

responses_df = pd.DataFrame(responses, columns=["response"])
responses_df

                                            response
0  고객님, 안녕하세요. 저희 서비스를 이용해 주셔서 감사합니다.\n\n구입하신 물건을...
1  오, 반품하고 싶은 물건이 있군요! 걱정 마세요, 간단한 방법이 있어요. 우선, 여...
2  물건을 반품하고 환불받으시려면 몇 가지 절차를 따라야 합니다. 먼저, 구매하신 물건...

In [6]:
prompt_eval = f"""
응답 텍스트에 대한 평가(1~5, 5점 만점)를 평가항목에 따라 예시와 같이 JSON형식으로 만들어주세요.

평가항목:
- 정확성: 응답 내용의 사실적 정확도와 일관성
- 일관성: 지정된 역할이나 톤을 응답이 꾸준히 유지하는 정도
- 톤 적절성: 목표 사용자나 상황에 맞는 어조/스타일 사용 여부
- 포맷 적합성: 요구된 출력 형식과 논리 구조를 제대로 따른 정도

예시:
[
    {{"정확성": 5, "일관성": 5, "톤 적절성": 5, "포맷 적합성": 5 }},
    {{"정확성": 4, "일관성": 4, "톤 적절성": 4, "포맷 적합성": 4 }},
    {{"정확성": 3, "일관성": 3, "톤 적절성": 3, "포맷 적합성": 3 }}
]

응답 텍스트:
{responses_df.to_markdown()} # LLM이 입력과 출력에 markdown에 대한 학습이 잘되어 있어 변환하는 것이 좋다.
"""

print(prompt_eval)

응답 텍스트에 대한 평가(1~5, 5점 만점)를 평가항목에 따라 예시와 같이 JSON형식으로 만들어주세요.

평가항목:
- 정확성: 응답 내용의 사실적 정확도와 일관성
- 일관성: 지정된 역할이나 톤을 응답이 꾸준히 유지하는 정도
- 톤 적절성: 목표 사용자나 상황에 맞는 어조/스타일 사용 여부
- 포맷 적합성: 요구된 출력 형식과 논리 구조를 제대로 따른 정도

예시:
[
    {"정확성": 5, "일관성": 5, "톤 적절성": 5, "포맷 적합성": 5 },
    {"정확성": 4, "일관성": 4, "톤 적절성": 4, "포맷 적합성": 4 },
    {"정확성": 3, "일관성": 3, "톤 적절성": 3, "포맷 적합성": 3 }
]

응답 텍스트:
|    | response                                                                                                                                                                                                                                        |
|---:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | 고객님, 안녕하세요. 저희 서비스를 이용해 주셔서 감사합니다.                                                                                                                                                                                     |
|    |                                                                                                                                                                                                                                                 |
|    | 구입하신 물건을 반품하고 환불받으시려면 다음의 절차를 따라주시기 바랍니다:                                                                                                                                                                      |
|    |                                                                                                                                                                                                                                                 |
|    | 1. **반품 기간 확인**: 구입 후 반품 가능한 기간을 확인해 주세요. 일반적으로 많은 제품이 구입일로부터 7일 이내에 반품이 가능합니다.                                                                                                              |
|    |                                                                                                                                                                                                                                                 |
|    | 2. **영수증 준비**: 구입 시 받은 영수증 또는 주문 확인 이메일을 준비해 주세요.                                                                                                                                                                  |
|    |                                                                                                                                                                                                                                                 |
|    | 3. **고객센터 문의**: 반품 의사를 확인하기 위해 저희 고객센터로 문의하시면, 필요한 절차와 상세한 안내를 제공해 드립니다.                                                                                                                        |
|    |                                                                                                                                                                                                                                                 |
|    | 4. **상품 포장**: 반품할 상품은 원래의 포장 상태로, 모든 구성품과 함께 반환해 주세요.                                                                                                                                                           |
|    |                                                                                                                                                                                                                                                 |
|    | 5. **배송 방법 선택**: 상품을 반품하시는 방법에 대해 안내드릴 것입니다. 고객님께서 선택하신 방법에 따라 배송해 주시면 됩니다.                                                                                                                   |
|    |                                                                                                                                                                                                                                                 |
|    | 반품 및 환불 절차에 대한 추가적인 문의가 있으시면 언제든지 저희 고객센터로 연락 주시기 바랍니다. 감사합니다.                                                                                                                                    |
|  1 | 오, 반품하고 싶은 물건이 있군요! 걱정 마세요, 간단한 방법이 있어요. 우선, 여러분이 구입한 곳의 반품 정책을 확인해야 해요. 일반적으로는 영수증이나 주문번호가 필요할 수 있어요. 그 다음엔 물건을 원래 상태로 포장해주고, 반품 주소를 확인해요.   |
|    |                                                                                                                                                                                                                                                 |
|    | 그 후, 고객 서비스에 연락하거나 웹사이트에서 반품 양식을 작성하면 돼요. 때로는 반품 라벨도 제공해주니까 그걸 붙여서 보내면 끝! 환불은 보통 몇 일 내로 처리된답니다. 더 궁금한 점 있으면 언제든 물어보세요! 😊                                   |
|  2 | 물건을 반품하고 환불받으시려면 몇 가지 절차를 따라야 합니다. 먼저, 구매하신 물건의 반품 정책을 확인해 주세요. 일반적으로 반품은 구매 후 일정 기간 내에 가능하며, 사용하지 않거나 포장 상태가 원래 그대로여야 합니다.                            |
|    |                                                                                                                                                                                                                                                 |
|    | 대부분의 경우, 물건과 함께 받은 영수증이나 구매 확인서를 포함하여 반품 요청을 하셔야 합니다. 반품 방법은 온라인 또는 오프라인에 따라 다를 수 있으니, 해당 판매자의 웹사이트나 고객 서비스에 문의하시면 보다 구체적인 안내를 받으실 수 있습니다. |
|    |                                                                                                                                                                                                                                                 |
|    | 환불은 반품이 처리된 후 일정 시간 내에 진행됩니다. 다른 질문이 있으시면 언제든지 문의해 주세요.                                                                                                                                                 | # LLM이 입력과 출력에 markdown에 대한 학습이 잘되어 있어 변환하는 것이 좋다.

In [7]:
response = client.chat.completions.create(
    messages=[
        {"role": "user", "content": prompt_eval}
    ],
    model="gpt-4o",
    response_format={"type": "json_object"}
)
evaluation = response.choices[0].message.content
print(evaluation)
print(type(evaluation))

{
    "responses": [
        {
            "정확성": 5,
            "일관성": 5,
            "톤 적절성": 5,
            "포맷 적합성": 5
        },
        {
            "정확성": 4,
            "일관성": 4,
            "톤 적절성": 4,
            "포맷 적합성": 4
        },
        {
            "정확성": 5,
            "일관성": 5,
            "톤 적절성": 5,
            "포맷 적합성": 5
        }
    ]
}
<class 'str'>

In [9]:
import json

evals = json.loads(evaluation) # 문자열을 Dictionary로 변환

print(evals)

all_data = []
for scores in evals["responses"]:
    all_data.append({**scores})

eval_df = pd.DataFrame(all_data)
eval_df

{'responses': [{'정확성': 5, '일관성': 5, '톤 적절성': 5, '포맷 적합성': 5}, {'정확성': 4, '일관성': 4, '톤 적절성': 4, '포맷 적합성': 4}, {'정확성': 5, '일관성': 5, '톤 적절성': 5, '포맷 적합성': 5}]}

   정확성  일관성  톤 적절성  포맷 적합성
0    5    5      5       5
1    4    4      4       4
2    5    5      5       5

In [ ]:
roles_models_df = pd.DataFrame(roles_models, columns=["role", "model"])
roles_models_df

                                                role        model
0           당신은 격식을 갖춰 회사의 공식톤으로 고객과 소통하는 고객 상담원입니다.  gpt-4o-mini
1                  당신은 지나치게 캐주얼한 톤으로 응대하는 고객 상담원입니다.  gpt-4o-mini
2  당신은 공식 톤이지만 중요 세부 정보를 누락해 사실성 부족을 느끼게 하는 고객 상담...  gpt-4o-mini

In [ ]:
result_df = pd.concat([roles_models_df, responses_df, eval_df], axis=1)
result_df

,role,model,response,정확성,일관성,톤 적절성,포맷 적합성
0,당신은 격식을 갖춰 회사의 공식톤으로 고객과 소통하는 고객 상담원입니다.,gpt-4o-mini,"고객님, 안녕하세요.\n\n구입하신 물건을 반품하고 환불 받으시려면 아래의 절차를 ...",5,5,5,5
1,당신은 지나치게 캐주얼한 톤으로 응대하는 고객 상담원입니다.,gpt-4o-mini,안녕하세요! 어제 구매하신 물건 반품하고 환불받고 싶으시군요? 걱정 마세요! 보통 ...,4,4,5,5
2,당신은 공식 톤이지만 중요 세부 정보를 누락해 사실성 부족을 느끼게 하는 고객 상담...,gpt-4o-mini,"물건을 반품하고 환불받으시려면, 구입하신 상점의 반품 정책을 확인하시는 것이 가장 ...",4,5,5,5

In [ ]:
result_df.to_csv("result_evaluation_2.csv", index=False)

In [ ]:
result_df

,role,model,response,정확성,일관성,톤 적절성,포맷 적합성
0,당신은 격식을 갖춰 회사의 공식톤으로 고객과 소통하는 고객 상담원입니다.,gpt-4o-mini,"고객님, 안녕하세요.\n\n구입하신 물건을 반품하고 환불 받으시려면 아래의 절차를 ...",5,5,5,5
1,당신은 지나치게 캐주얼한 톤으로 응대하는 고객 상담원입니다.,gpt-4o-mini,안녕하세요! 어제 구매하신 물건 반품하고 환불받고 싶으시군요? 걱정 마세요! 보통 ...,4,4,5,5
2,당신은 공식 톤이지만 중요 세부 정보를 누락해 사실성 부족을 느끼게 하는 고객 상담...,gpt-4o-mini,"물건을 반품하고 환불받으시려면, 구입하신 상점의 반품 정책을 확인하시는 것이 가장 ...",4,5,5,5

In [ ]:
# 각 지표별 평균 점수
result_df[["정확성","일관성","톤 적절성","포맷 적합성"]].mean()

정확성       4.333333
일관성       4.666667
톤 적절성     5.000000
포맷 적합성    5.000000
dtype: float64

In [ ]:
# 특정 조건 필터링: 정확성 3 이하인 사례 출력
result_df[result_df["정확성"] <= 3][["model","role","정확성","response"]]

Empty DataFrame
Columns: [model, role, 정확성, response]
Index: []