In [ ]:
# !pip install -U openai

In [1]:
# from google.colab import userdata
import os
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

# 환경 변수에서 가져오기
api_key = os.getenv("OPENAI_API_KEY")

# Colab에 저장한 Secret에서 API 키 가져와 환경 변수에 등록
os.environ["OPENAI_API_KEY"] = api_key

# Colab에 저장한 Secret에서 API 키 가져와 환경 변수에 등록
# os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

import openai

client = openai.OpenAI()

In [2]:
import time
from pprint import pprint

roles_models = [
    ("당신은 친절한 초등학교 과학선생님입니다.", "gpt-4o-mini"),
    ("당신은 물리학과 대학교수입니다.", "gpt-4o-mini"),
    ("당신은 친절한 초등학교 과학선생님입니다.", "gpt-3.5-turbo")
]
prompt = "양자이론이 뭐에요?"
responses = []

for role, model in roles_models:
    response = client.chat.completions.create(
        messages= [
            {"role": "system", "content": role},
            {"role": "user", "content": prompt}
        ],
        model=model
    )
    responses.append(response.choices[0].message.content)
    time.sleep(1)

# 응답 내용 추출
pprint(responses)

['양자이론은 물질과 에너지가 아주 작은 규모에서 어떻게 행동하는지를 설명하는 과학 이론이에요. 주로 원자와 소립자, 즉 전자, 프로톤, '
 '중성자 같은 아주 작은 입자들을 다룹니다. \n'
 '\n'
 '양자이론의 몇 가지 중요한 개념은 다음과 같아요:\n'
 '\n'
 '1. **양자화**: 에너지와 같은 일부 물리적 양이 연속적인 값이 아니라, 특정한 불연속적인 값으로만 존재할 수 있다는 거예요. 예를 '
 '들어, 전자는 특정한 에너지 준위에서만 존재할 수 있어요.\n'
 '\n'
 '2. **파동-입자 이중성**: 입자들은 입자의 성질뿐만 아니라 파동의 성질도 가지는데, 예를 들어 빛은 입자로도, 파동으로도 행동할 수 '
 '있어요.\n'
 '\n'
 '3. **불확정성 원리**: 어떤 입자의 위치와 속도를 동시에 정확하게 알 수 없다는 원리예요. 즉, 한 가지를 정확하게 알면 다른 '
 '하나는 불확실해질 수 있어요.\n'
 '\n'
 '양자이론은 현대 물리학의 기초를 이루고 있으며, 많은 기술, 예를 들어 반도체, 레이저, MRI 같은 것들이 이 이론에 기반하고 있어요. '
 '조금 복잡하지만, 아주 흥미로운 분야랍니다!',
 '양자이론(quantum theory)은 물리학의 한 분야로, 보다 작은 스케일인 원자나 아원자 입자의 행동을 설명합니다. 고전 물리학으로 '
 '설명할 수 없는 현상들을 이해하고 예측하기 위해 개발되었습니다. 주된 개념으로는 다음과 같은 것들이 있습니다:\n'
 '\n'
 '1. **양자화**: 에너지와 같은 물리적 양이 연속적이 아니라 불연속적인 값(양자)으로 존재한다는 개념입니다. 예를 들어, 빛은 '
 '연속적인 전자기파가 아니라 양자화된 광자(빛의 입자)로 설명됩니다.\n'
 '\n'
 '2. **중첩 원리**: 입자가 여러 상태를 동시에 가질 수 있다는 원리입니다. 이 때문에 양자 시스템은 관측되기 전까지 여러 상태의 '
 '조합으로 존재합니다.\n'
 '\n'
 '3. **불확정성 원리**: 하이젠베르크의 불확정성 원리로, 입자의 위치와 운동량을 동시에 정확하게 측정할 수 없다는 것입니다. 이는 '
 '양자 세계의 본질적인 특성으로, 고전 물리학의 직관과는 매우 다릅니다.\n'
 '\n'
 '4. **양자 얽힘**: 두 개 이상의 입자가 서로 강하게 상관되어, 하나의 상태가 결정되면 다른 입자의 상태도 즉시 결정되는 '
 '현상입니다. 이는 공간적으로 멀리 떨어져 있는 입자들 간에도 적용됩니다.\n'
 '\n'
 '양자이론은 현대 물리학의 기초를 이루며, 원자론, 분자 물리학, 반도체 물리학, 양자 컴퓨팅 등 다양한 분야에 응용됩니다. 또한, 고전 '
 '물리학의 한계를 뛰어넘는 대단한 혁신적 아이디어로 여겨지고 있습니다.',
 '양자이론은 물리학의 한 분야로, 원자나 분자 등의 물질에서 일어나는 현상을 설명하는 이론입니다. 양자이론은 미시세계에서 일어나는 현상을 '
 '이해하는데 사용되며, 물리학의 기본 원리들 중 하나입니다. 양자이론은 우리가 주변 세계를 이해하고 설명하는데 도움을 줄 수 있습니다. '
 '예를 들어, 양자이론은 빛의 파동-입자 이중성에 대해 설명하거나, 원자나 분자가 빛과 상호작용하는 방식을 이해하는 데 중요한 역할을 '
 '합니다.양자이론은 현대 물리학 전반에 걸쳐 중요한 역할을 하고 있습니다.']

In [3]:
import pandas as pd

responses_df = pd.DataFrame(responses, columns=["response"])
responses_df

                                            response
0  양자이론은 물질과 에너지가 아주 작은 규모에서 어떻게 행동하는지를 설명하는 과학 이...
1  양자이론(quantum theory)은 물리학의 한 분야로, 보다 작은 스케일인 원...
2  양자이론은 물리학의 한 분야로, 원자나 분자 등의 물질에서 일어나는 현상을 설명하는...

In [4]:
prompt_eval = f"""
응답 텍스트에 대한 평가(1~5, 5점 만점)를 평가항목에 따라 예시와 같이 JSON형식으로 만들어주세요.

평가항목:
- 정확성: 응답 내용의 사실적 정확도와 일관성
- 일관성: 지정된 역할이나 톤을 응답이 꾸준히 유지하는 정도
- 톤 적절성: 목표 사용자나 상황에 맞는 어조/스타일 사용 여부
- 포맷 적합성: 요구된 출력 형식과 논리 구조를 제대로 따른 정도

예시:
[
    {{"정확성": 5, "일관성": 5, "톤 적절성": 5, "포맷 적합성": 5 }},
    {{"정확성": 4, "일관성": 4, "톤 적절성": 4, "포맷 적합성": 4 }},
    {{"정확성": 3, "일관성": 3, "톤 적절성": 3, "포맷 적합성": 3 }}
]

응답 텍스트:
{responses_df.to_markdown()} # LLM이 입력과 출력에 markdown에 대한 학습이 잘되어 있어 변환하는 것이 좋다.
"""

print(prompt_eval)

응답 텍스트에 대한 평가(1~5, 5점 만점)를 평가항목에 따라 예시와 같이 JSON형식으로 만들어주세요.

평가항목:
- 정확성: 응답 내용의 사실적 정확도와 일관성
- 일관성: 지정된 역할이나 톤을 응답이 꾸준히 유지하는 정도
- 톤 적절성: 목표 사용자나 상황에 맞는 어조/스타일 사용 여부
- 포맷 적합성: 요구된 출력 형식과 논리 구조를 제대로 따른 정도

예시:
[
    {"정확성": 5, "일관성": 5, "톤 적절성": 5, "포맷 적합성": 5 },
    {"정확성": 4, "일관성": 4, "톤 적절성": 4, "포맷 적합성": 4 },
    {"정확성": 3, "일관성": 3, "톤 적절성": 3, "포맷 적합성": 3 }
]

응답 텍스트:
|    | response                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|---:|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | 양자이론은 물질과 에너지가 아주 작은 규모에서 어떻게 행동하는지를 설명하는 과학 이론이에요. 주로 원자와 소립자, 즉 전자, 프로톤, 중성자 같은 아주 작은 입자들을 다룹니다.                                                                                                                                                                                                                                                                                                      |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 양자이론의 몇 가지 중요한 개념은 다음과 같아요:                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 1. **양자화**: 에너지와 같은 일부 물리적 양이 연속적인 값이 아니라, 특정한 불연속적인 값으로만 존재할 수 있다는 거예요. 예를 들어, 전자는 특정한 에너지 준위에서만 존재할 수 있어요.                                                                                                                                                                                                                                                                                           |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 2. **파동-입자 이중성**: 입자들은 입자의 성질뿐만 아니라 파동의 성질도 가지는데, 예를 들어 빛은 입자로도, 파동으로도 행동할 수 있어요.                                                                                                                                                                                                                                                                                                                                         |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 3. **불확정성 원리**: 어떤 입자의 위치와 속도를 동시에 정확하게 알 수 없다는 원리예요. 즉, 한 가지를 정확하게 알면 다른 하나는 불확실해질 수 있어요.                                                                                                                                                                                                                                                                                                                           |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 양자이론은 현대 물리학의 기초를 이루고 있으며, 많은 기술, 예를 들어 반도체, 레이저, MRI 같은 것들이 이 이론에 기반하고 있어요. 조금 복잡하지만, 아주 흥미로운 분야랍니다!                                                                                                                                                                                                                                                                                                      |
|  1 | 양자이론(quantum theory)은 물리학의 한 분야로, 보다 작은 스케일인 원자나 아원자 입자의 행동을 설명합니다. 고전 물리학으로 설명할 수 없는 현상들을 이해하고 예측하기 위해 개발되었습니다. 주된 개념으로는 다음과 같은 것들이 있습니다:                                                                                                                                                                                                                                          |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 1. **양자화**: 에너지와 같은 물리적 양이 연속적이 아니라 불연속적인 값(양자)으로 존재한다는 개념입니다. 예를 들어, 빛은 연속적인 전자기파가 아니라 양자화된 광자(빛의 입자)로 설명됩니다.                                                                                                                                                                                                                                                                                      |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 2. **중첩 원리**: 입자가 여러 상태를 동시에 가질 수 있다는 원리입니다. 이 때문에 양자 시스템은 관측되기 전까지 여러 상태의 조합으로 존재합니다.                                                                                                                                                                                                                                                                                                                                |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 3. **불확정성 원리**: 하이젠베르크의 불확정성 원리로, 입자의 위치와 운동량을 동시에 정확하게 측정할 수 없다는 것입니다. 이는 양자 세계의 본질적인 특성으로, 고전 물리학의 직관과는 매우 다릅니다.                                                                                                                                                                                                                                                                              |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 4. **양자 얽힘**: 두 개 이상의 입자가 서로 강하게 상관되어, 하나의 상태가 결정되면 다른 입자의 상태도 즉시 결정되는 현상입니다. 이는 공간적으로 멀리 떨어져 있는 입자들 간에도 적용됩니다.                                                                                                                                                                                                                                                                                     |
|    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|    | 양자이론은 현대 물리학의 기초를 이루며, 원자론, 분자 물리학, 반도체 물리학, 양자 컴퓨팅 등 다양한 분야에 응용됩니다. 또한, 고전 물리학의 한계를 뛰어넘는 대단한 혁신적 아이디어로 여겨지고 있습니다.                                                                                                                                                                                                                                                                           |
|  2 | 양자이론은 물리학의 한 분야로, 원자나 분자 등의 물질에서 일어나는 현상을 설명하는 이론입니다. 양자이론은 미시세계에서 일어나는 현상을 이해하는데 사용되며, 물리학의 기본 원리들 중 하나입니다. 양자이론은 우리가 주변 세계를 이해하고 설명하는데 도움을 줄 수 있습니다. 예를 들어, 양자이론은 빛의 파동-입자 이중성에 대해 설명하거나, 원자나 분자가 빛과 상호작용하는 방식을 이해하는 데 중요한 역할을 합니다.양자이론은 현대 물리학 전반에 걸쳐 중요한 역할을 하고 있습니다. | # LLM이 입력과 출력에 markdown에 대한 학습이 잘되어 있어 변환하는 것이 좋다.

In [12]:
# responses_df.to_markdown()
responses_df.to_csv("responses.csv", index=False)

In [5]:
response = client.chat.completions.create(
    messages=[
        {"role": "user", "content": prompt_eval}
    ],
    model="gpt-4o",
    response_format={"type": "json_object"}
)
evaluation = response.choices[0].message.content
print(evaluation)
print(type(evaluation))

   {
       "평가": [
           {
               "정확성": 5,
               "일관성": 5,
               "톤 적절성": 5,
               "포맷 적합성": 5
           },
           {
               "정확성": 5,
               "일관성": 5,
               "톤 적절성": 5,
               "포맷 적합성": 5
           },
           {
               "정확성": 4,
               "일관성": 4,
               "톤 적절성": 4,
               "포맷 적합성": 4
           }
       ]
   }
<class 'str'>

In [8]:
import json

evals = json.loads(evaluation) # 문자열을 Dictionary로 변환

print(evals)

all_data = []
for scores in evals["평가"]: # Changed 'responses' to '평가'
    all_data.append({**scores})

eval_df = pd.DataFrame(all_data)
eval_df

{'평가': [{'정확성': 5, '일관성': 5, '톤 적절성': 5, '포맷 적합성': 5}, {'정확성': 5, '일관성': 5, '톤 적절성': 5, '포맷 적합성': 5}, {'정확성': 4, '일관성': 4, '톤 적절성': 4, '포맷 적합성': 4}]}

   정확성  일관성  톤 적절성  포맷 적합성
0    5    5      5       5
1    5    5      5       5
2    4    4      4       4

In [9]:
roles_models_df = pd.DataFrame(roles_models, columns=["role", "model"])
roles_models_df

                     role          model
0  당신은 친절한 초등학교 과학선생님입니다.    gpt-4o-mini
1       당신은 물리학과 대학교수입니다.    gpt-4o-mini
2  당신은 친절한 초등학교 과학선생님입니다.  gpt-3.5-turbo

In [10]:
result_df = pd.concat([roles_models_df, responses_df, eval_df], axis=1)
result_df

,role,model,response,정확성,일관성,톤 적절성,포맷 적합성
0,당신은 친절한 초등학교 과학선생님입니다.,gpt-4o-mini,양자이론은 물질과 에너지가 아주 작은 규모에서 어떻게 행동하는지를 설명하는 과학 이...,5,5,5,5
1,당신은 물리학과 대학교수입니다.,gpt-4o-mini,"양자이론(quantum theory)은 물리학의 한 분야로, 보다 작은 스케일인 원...",5,5,5,5
2,당신은 친절한 초등학교 과학선생님입니다.,gpt-3.5-turbo,"양자이론은 물리학의 한 분야로, 원자나 분자 등의 물질에서 일어나는 현상을 설명하는...",4,4,4,4

In [11]:
result_df.to_csv("result_evaluation.csv", index=False)

In [ ]:
result_df

In [ ]:
# 각 지표별 평균 점수
result_df[["정확성","일관성","톤 적절성","포맷 적합성"]].mean()

In [ ]:
# 특정 조건 필터링: 정확성 3 이하인 사례 출력
result_df[result_df["정확성"] <= 3][["model","role","정확성","response"]]